Feat/metric collection and submission to proxy
hummingbot/hummingbot pull request #4657
Opened 2021-11-05 18:26 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2021-11-08 19:03 UTC, martinkou requested changes

2021-11-08 19:03 UTC, martinkou commented on gateway/src/chains/ethereum/ethereum.ts
> +    logger.http(metricFormat);
This feels like a hack to me. In Datadog, metrics are separated from logs - they are not the same entities. Do we have separate endpoints / functionalities in the reporting proxy API for logs and metrics?

2021-11-15 15:00 UTC, vic-en commented
Notion page for ongoing discussion with Michael Chuang - https://www.notion.so/hummingbot/Requirements-for-Gateway-Datadog-usage-404c7391c9a446539688ff5a645c97f5

2021-12-17 18:42 UTC, martinkou requested changes

2021-12-17 18:42 UTC, martinkou commented on gateway/src/services/logger.ts
> +  host: 'https://api.coinalpha.com',
Please don't add "https://" to the host field. Refer to the URI standard.

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

2021-12-20 18:55 UTC, mifeng commented
Closing in favor of https://github.com/CoinAlpha/hummingbot/pull/10

2021-12-20 18:55 UTC, closed without merging