(fix) Refactors the Coinbase Pro connector to use the `WebAssistants`…
hummingbot/hummingbot pull request #4919
Opened 2021-12-16 05:02 UTC by petioptrv

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Adapts Coinbase Pro connector to use the `WebAssistants` layer
- Adds authenticator capabilities to the `WebAssistants` layer

**Tests performed by the developer**:
- Tests cases for the changes
- Minor fixes on some of the Gate.io tests

**Tips for QA testing**:
- The full range of Coinbase Pro connector's communication with the server (posting order, cancelling orders, receiving order updates, receiving order book data, etc)

2021-12-16 15:48 UTC, rapcmia commented
Tested on both local and AWS and order creation and cancellation seems to be working ok. However, the client is getting `unexpected error in user stream listener loop...` on every time it creates order. 

![image](https://user-images.githubusercontent.com/73840223/146402582-e5c15c1e-e6fa-459f-aec1-a6a37599aa00.png)

```
2021-12-16 22:27:49,365 - 1949 - hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 562, in hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange.CoinbaseProExchange._user_stream_event_listener
    event_type = content.get("type")
AttributeError: 'CoinbaseProOrderBookMessage' object has no attribute 'get'
2021-12-16 22:27:49,406 - 1949 - hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange - INFO - Created OrderType.LIMIT_MAKER sell order sell-ETH-USDT-1639664869002001 for 0.00400000 ETH-USDT.
2021-12-16 22:27:49,422 - 1949 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1639664869.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.00400000", "price": "4106.78", "order_id": "sell-ETH-USDT-1639664869002001", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "coinbase_pro"}
2021-12-16 22:27:54,366 - 1949 - hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 562, in hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange.CoinbaseProExchange._user_stream_event_listener
    event_type = content.get("type")
AttributeError: 'CoinbaseProOrderBookMessage' object has no attribute 'get'
```

Steps to reproduce:
1. Setup Pure market-making on Coinbase Pro
2. Start the bot and monitor the order creation


Log and config files: [pmm-test.zip](https://github.com/CoinAlpha/hummingbot/files/7728667/pmm-test.zip)

2021-12-16 21:03 UTC, aarmoa requested changes
I could not finish reviewing all the PR. I submit the issues I have already found to allow Petio to start working on them.

2021-12-16 21:03 UTC, aarmoa commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                        await asyncio.sleep(CONSTANTS.REST_API_LIMIT_COOLDOWN)
Here we should be calling self._sleep

2021-12-16 21:03 UTC, aarmoa commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                        await asyncio.sleep(CONSTANTS.REST_API_LIMIT_COOLDOWN)
Here we should be calling self._sleep

2021-12-16 21:03 UTC, aarmoa commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                await asyncio.sleep(delta)
Here we should be calling self._sleep

2021-12-17 05:26 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +
Addressed

2021-12-17 05:32 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +        factory = cls.get_shared_web_assistants_factory()
I traced down `OrderBookTracker._update_last_trade_prices_loop` on line 161 which calls this function on an instance of the data source, but doesn't pass in the the factory, which means that we'll be creating a new session every second

2021-12-17 05:33 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +            factory = CoinbaseProAPIOrderBookDataSource.get_shared_web_assistants_factory()
It will be created and set in the method

2021-12-17 05:35 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                        await asyncio.sleep(CONSTANTS.REST_API_LIMIT_COOLDOWN)
Addressed

2021-12-17 05:35 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                        await asyncio.sleep(CONSTANTS.REST_API_LIMIT_COOLDOWN)
Addressed

2021-12-17 05:35 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +                await asyncio.sleep(delta)
Addressed

2021-12-17 12:52 UTC, aarmoa commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_api_order_book_data_source.py
> +        factory = cls.get_shared_web_assistants_factory()
I think it is better to discuss the possibility to add the session as one of the parameters that OrderBookTracker receives in the init method, for it to have it to interact with the data stream, and not add a class variable or a global. By the way, the subclasses of the order book tracker (the ones created for each connector) do keep a reference to the shared session (or factory in this case). If we require it also for the functions in the superclass we should let it receive it too.

2021-12-17 15:06 UTC, aarmoa requested changes

2021-12-17 15:06 UTC, aarmoa commented on test/hummingbot/connector/exchange/coinbase_pro/test_coinbase_pro_exchange.py
> +from typing import List, Awaitable, Dict
```suggestion
from typing import Awaitable, Dict, List
```

2021-12-17 15:06 UTC, aarmoa commented on test/hummingbot/core/web_assistant/connections/test_data_types.py
> +    RESTMethod, RESTResponse, EndpointRESTRequest
```suggestion
    EndpointRESTRequest, RESTMethod, RESTResponse
```

2021-12-17 15:06 UTC, aarmoa commented on test/hummingbot/core/web_assistant/test_ws_assistant.py
> +    WSRequest, WSResponse, RESTRequest
```suggestion
    RESTRequest, WSRequest, WSResponse
```

2021-12-20 03:20 UTC, petioptrv commented on hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx
> +    CoinbaseProRESTRequest, build_coinbase_pro_web_assistant_factory
For this one, I think `isort` ordered it like this because of capital C

2021-12-22 03:04 UTC, merged