Fix/error on install source
hummingbot/hummingbot pull request #5140
Opened 2022-02-24 09:52 UTC by sparksun

**Before submitting this PR, please make sure**:

[Yes] Your code builds clean without any errors or warnings
[Yes] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
When following the  [installation documentation](https://hummingbot.org/installation/source/) for source installation (AWS Ubuntu Server 20.04 LTS (HVM), SSD Volume Type 64bit x86), two errors are encountered. One is a lack of necessary imports, and one is a C++ type error, although it can work with my Mac. so I fixed it. This commit is related to [issue 5107](https://github.com/hummingbot/hummingbot/issues/5107)

**Tests performed by the developer**:
I try it work both ubunta and mac

**Tips for QA testing**:
You can try create an Ubuntu Server 20.04 LTS  instace on AWS, then follow [installation documentation](https://hummingbot.org/installation/source/)  try source install. you will got follow error on compile step:

`(hummingbot) ubuntu@ip-172-31-2-54:~/hummingbot$ ./compile
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
Compiling hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx because it changed.
Compiling hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx because it changed.
[1/2] Cythonizing hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                quote_currency: str,
                order_type: OrderType,
                order_side: TradeType,
                amount: Decimal,
                price: Decimal = s_decimal_nan,
                is_maker: Optional[bool] = None) -> AddedToCostTradeFee:
                                  ^
------------------------------------------------------------

hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx:1360:35: 'bool' is not a constant, variable or function identifier
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1274, in cythonize_one_helper
    return cythonize_one(*m)
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
[2/2] Cythonizing hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                    status_report_interval: float = 900,
                    hb_app_notification: bool = False,
                    risk_factor: Decimal = Decimal("0.5"),
                    order_amount_shape_factor: Decimal = Decimal("0.0"),
                    execution_timeframe: str = "infinite",
                    execution_state: ConditionalExecutionState = RunAlwaysExecutionState(),
                                    ^
------------------------------------------------------------

hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx:86:37: undeclared name not builtin: ConditionalExecutionState
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1274, in cythonize_one_helper
    return cythonize_one(*m)
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1274, in cythonize_one_helper
    return cythonize_one(*m)
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/setup.py", line 153, in <module>
    main()
  File "/home/ubuntu/hummingbot/setup.py", line 140, in main
    ext_modules=cythonize(cython_sources, compiler_directives=compiler_directives, **cython_kwargs),
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1118, in cythonize
    result.get(99999)  # seconds
  File "/home/ubuntu/anaconda3/envs/hummingbot/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
Cython.Compiler.Errors.CompileError: hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
`

2022-03-29 13:04 UTC, martinkou requested changes

2022-03-29 13:04 UTC, martinkou commented on hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
>  from libcpp cimport bool
The recommended practice is to do `from libcpp cimport bool as cppbool`, not import it as a Python name. Refer to `paper_trade_exchange.pyx` for how it's done.

2022-03-29 13:06 UTC, martinkou requested changes

2022-03-29 13:06 UTC, martinkou commented on hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
> +from libcpp import bool as cppbool
There's no real use of C++ bool anywhere in the file - all bool types are just regular Python booleans. The `from libcpp cimport bool` should be deleted instead.

2022-04-04 02:34 UTC, JeremyKono commented
Hi @sparksun. Please make changes accordingly to the comments left by the reviewer.

2022-04-04 02:35 UTC, CryptoGodfatherVA4 approved these changes

2022-04-04 02:36 UTC, CryptoGodfatherVA4 approved these changes

2022-04-04 02:36 UTC, CryptoGodfatherVA4 approved these changes

2022-04-12 03:40 UTC, aarmoa commented
The issue has been solved with other PR related to Avellaneda. This PR should not be required.

2022-04-20 01:31 UTC, closed without merging