change ceiling and floor price to percentage
hummingbot/hummingbot pull request #5179
Opened 2022-03-10 08:53 UTC by 3XMlimited

New set up via choosing a percentage for floor and ceiling instead of price

Regarding the request for "price_band_refresh_time", looks redundant as price bands are reset based on the current price ("get_price") every-time "order_refresh_time" is checked while send orders for PMM

2022-04-25 03:32 UTC, aarmoa commented
@3XMlimited please review the PR. It is currently pointing to master branch as its base instead of development. Also please include the link to the PRP created for the community to vote for the change.

2022-05-27 06:44 UTC, mhrvth requested changes
-- Review submitted in representation of the Hummingbot Foundation Technical DAO

2022-05-28 03:36 UTC, leastchaos commented
I think this pr should be closed as the feature is already added in https://github.com/hummingbot/hummingbot/pull/5181

2022-06-04 04:45 UTC, aarmoa commented
@cardosofede @JeremyKono please close this PR

2022-06-14 23:56 UTC, closed without merging