Feature: Remember the last strategy created or imported
hummingbot/hummingbot pull request #5246
Opened 2022-04-21 15:28 UTC by carlosmiei

While using hummingbot, I would start it and stop several times, but most of the time I started it again I wanted to use the previous strategy I had used. Having to import it every time is painful, especially when we have tons of different strategies, and we are not sure what's the strategy name.

To solve this issue, I implemented a feature that uses the global config file to store/retrieve the last strategy created or imported, making things a lot easier :)

This was done simply by saving the name of the strategy every time the user imports or creates a strategy and creating a command ("previous") that can be invoked by the user, inform the name of the stored strategy, if it exists, and collects the answer (calling the import commands afterward).

I've also added tests and the coverage is over 80%.

Demo:
![HummingbotPreviousCommandDemo](https://user-images.githubusercontent.com/43336371/164492659-77d767ec-7712-43f7-9f32-2df9697f5505.gif)

Continues: #3872

2022-04-26 14:33 UTC, carlosmiei commented
Snapshot proposal: https://snapshot.org/#/hbot-prp.eth/proposal/0xbd0c7db686c4072d21d3c621beffb0a5c868c0e906caffab4e0540557955ba8f

2022-05-04 12:29 UTC, leastchaos requested changes
- tech review dao

2022-05-04 12:29 UTC, leastchaos commented on hummingbot/client/command/previous_strategy_command.py
> +            prompt=f"Dou you want to import the previously stored strategy? ({file_name}) (Yes/No) >>>",
the prompt issue is due to the use of the word strategy as the completer in hummingbot/client/ui/completer.py looks for strategy in the prompt first. One possible method is to change to previously stored config to resolve this. but up to you.

2022-05-04 12:29 UTC, leastchaos commented on hummingbot/client/command/previous_strategy_command.py
> +            prompt=f"Dou you want to import the previously stored strategy? ({file_name}) (Yes/No) >>>",
also typo Dou -> Do

2022-05-04 12:29 UTC, leastchaos commented on test/hummingbot/client/command/test_previous_command.py
> +        self.app.previous_statrategy(option="")
typo? statrategy -> strategy?

2022-05-04 12:29 UTC, leastchaos commented on hummingbot/client/command/previous_strategy_command.py
> +    def previous_statrategy(
typo? statrategy -> strategy?

2022-05-04 12:29 UTC, leastchaos commented on hummingbot/client/command/previous_strategy_command.py
> +            self._notify(err_msg)
self._notify produce error. should be self.notify instead?

2022-05-12 00:01 UTC, JeremyKono commented
Hi @carlosmiei, one of the technical review DAO and our QA have commented issues on this PR. Please update them immediately or else we will close this PR. Thanks!

2022-05-12 08:18 UTC, carlosmiei commented
@JeremyKono done

2022-05-12 10:37 UTC, carlosmiei commented on hummingbot/client/command/previous_strategy_command.py
> +            prompt=f"Do you want to import the previously stored config? ({file_name}) (Yes/No) >>>",
fixed

2022-05-12 11:23 UTC, leastchaos approved these changes

2022-05-16 23:38 UTC, JeremyKono commented
Hi @carlosmiei, can you please check why the Github tests are failing for this PR and push a fix? Thanks!

2022-05-17 14:03 UTC, cardosofede commented
hi @carlosmiei, could you rebase with development?

2022-05-17 14:31 UTC, carlosmiei commented
@JeremyKono humm apparently it is related with the load_completer, will try to figure it out
![image](https://user-images.githubusercontent.com/43336371/168836314-87838f08-8a27-4b61-a2dd-3711b5ee0697.png)

2022-05-17 14:54 UTC, carlosmiei commented
@JeremyKono I found that the problem arises from the import order at the beginning of the file,
CLIMockingAssistant has to be the last import but the commit hook always sorts this putting it here. Is that a way to prevent this hook to change the file?
![image](https://user-images.githubusercontent.com/43336371/168841599-cd939828-0b1d-4040-acb9-278d5a0044ae.png)

2022-05-17 16:15 UTC, carlosmiei commented
@cardosofede @JeremyKono the `isort` command is breaking the build process, can't we disable it for certain files?

2022-05-17 19:23 UTC, cardosofede commented
hey @carlosmiei, run: conda activate hummingbot && pre-commit run --files $(git diff --name-only origin/development)
Be aware to have your dev branch updated with the last version of development of the official repo.
Let me know if you can or ping me on discord and I will help you

2022-05-17 20:57 UTC, carlosmiei commented
@cardosofede I explained earlier, the `isort` command is failing because it detects an unordered import but that import can not be ordered because it has to be the last one, or the test would fail (if you check other tests they all follow this). I've added now a comment so that isort will skip that import so hopefully will be ok now

2022-05-19 04:47 UTC, JeremyKono approved these changes

2022-05-19 04:48 UTC, merged