(fix) Fee override gets erased at hummingbot start
hummingbot/hummingbot pull request #5330
Opened 2022-05-21 00:34 UTC by MementoRC

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
When conf_fee_overrides_TEMPLATE.yml does not contain the same list of exchanges supported by hummingbot, load_yml_into_cm mechanic does not update the ConfigVar with the values from the user's conf_fee_overrides.yml and the save ends-up erasing the value set by the user in his file
The quick fix is to populate TEMPLATE with the correct list. The rest of the files are to add test methods

**Tests performed by the developer**:
Added tests to the suite. Verified that the conf_fee_overrides.yml no longer gets erased with default values but keep the modified values

**Tips for QA testing**:

2022-06-01 09:06 UTC, carlitogetaladajr commented
PRP Snapshot link:
https://snapshot.org/#/hbot-prp.eth/proposal/0xd7f87c4cfbe00a804a1152fdf3699ca5a363bd58ff87ea2b18fa631a5bf13198

2022-06-05 03:25 UTC, aarmoa requested changes
-- Reviewed in representation of the Hummingbot Foundation Technical DAO

2022-06-05 03:25 UTC, aarmoa commented on hummingbot/templates/conf_fee_overrides_TEMPLATE.yml
> +altmarkets_buy_percent_fee_deducted_from_returns:
Please remember to update the `template_version` when changing a `*TEMPLATE.yml` file

2022-06-05 03:25 UTC, aarmoa commented on test/conf/conf_fee_overrides.yml
> +kucoin_buy_percent_fee_deducted_from_returns:
The `conf_fee_overrides.yml` should not be added to the repository (no personal configuration file should be added).

2022-06-05 03:25 UTC, aarmoa commented on test/templates/conf_fee_overrides_TEMPLATE.yml
> +# [exchange name]_taker_fixed_fees:  # a list of lists of token-fee pairs (e.g. [["ETH", 1]])
Is it really necessary to create this file in the test folder? I would suggest creating the required test file in the test, inside a temporary directory that we make sure we delete when the test finish running.

2022-06-08 18:15 UTC, MementoRC commented
Created new PR: https://github.com/hummingbot/hummingbot/pull/5384 in an attempt to address reviewer's concerns

2022-06-08 18:15 UTC, closed without merging