Feat/bybit connector
hummingbot/hummingbot pull request #5354
Opened 2022-05-30 22:50 UTC by cardosofede

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Bybit Spot connector development. PRP related: https://snapshot.org/#/hbot-prp.eth/proposal/0x29bd6e24877d3c21050311f825095de7981b52bab5abb12b1a0374ae90f44a3f

**Tests performed by the developer**:

**Tips for QA testing**:

2022-06-01 01:29 UTC, aarmoa commented
@cardosofede please check the the unit tests. The validation workflow failed when running them.

2022-06-01 01:31 UTC, aarmoa commented on hummingbot/templates/conf_global_TEMPLATE.yml
> +bybit_api_secret: null
When changing a `*TEMPLATE.yml` file it is mandatory to also update its version number (first element in the same file)

2022-06-01 01:34 UTC, aarmoa requested changes
The version of `con_global_TEMPLATE.yml` needs to be updated. Also @cardosofede please check the unit tests. It seems that a couple of them are failing after the testnet domain fix.

2022-06-02 04:18 UTC, aarmoa approved these changes
The latest changes look good to me.

-- Reviewed in representation of the Hummingbot Foundation Technical DAO

2022-06-08 12:33 UTC, JeremyKono approved these changes

2022-06-08 12:38 UTC, merged