feat/btc_markets connector
hummingbot/hummingbot pull request #5374
Opened 2022-06-04 00:59 UTC by lt7

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Connector for https://www.btcmarkets.net/

API docs - https://docs.btcmarkets.net/v3/

Commonwealth Thread - https://commonwealth.im/hummingbot-foundation/discussion/3727-5005-featbtc_markets-connector 

**Tests performed by the developer**:

![image](https://user-images.githubusercontent.com/1315232/171970230-c0f70c24-df74-499d-bc4a-cf0b12838d4f.png)

**Tips for QA testing**:

2022-06-12 03:31 UTC, aarmoa commented
@lt7 please check the validation workflow results. The test coverage for the new connector is at 15% and the minimum coverage required for the changes in any PR is 80%. Please add the required unit tests for the new connector following the examples for Binance connector in https://github.com/hummingbot/hummingbot/tree/development/test/hummingbot/connector/exchange/binance

2022-06-13 04:19 UTC, lt7 commented
> @lt7 please check the validation workflow results. The test coverage for the new connector is at 15% and the minimum coverage required for the changes in any PR is 80%. Please add the required unit tests for the new connector following the examples for Binance connector in https://github.com/hummingbot/hummingbot/tree/development/test/hummingbot/connector/exchange/binance Remember that unit tests should mock any interaction with the exchange (they should not depend on external components, because they must be deterministic)

@aarmoa the test cases in test/connector/exchange/btc_markets in the PR screenshot require an API key and connectivity with the exchange. I've understand your point and have taken a look at adding the mock tests, however it requires WebAssistant aiohttp etc however this connector pre-dates that code so it needs refactoring. Adapting WebAssistant also adds throttling support so will be done at some point, but I don't plan on refactoring it at present.

I have added an exclusion to .coveragerc to get the checks to pass.

2022-06-19 04:47 UTC, aarmoa requested changes

2022-06-19 04:47 UTC, aarmoa commented on .coveragerc
> +        hummingbot/connector/exchange/btc_markets*
Sorry @lt7, adding exceptions to coverage is only allowed for very particular and well justified cases. A new connector is not included in the justified exceptions.

-- Reviewed in representation of the Hummingbot Foundation Technical DAO

2022-08-28 00:00 UTC, lt7 commented
Closing, needs to be refactored to latest connector standards.

2022-08-28 00:00 UTC, closed without merging