(fix) Quickstart failing for Pydantic config map
hummingbot/hummingbot pull request #5686
Opened 2022-09-09 22:15 UTC by MementoRC

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
quickstart seemed to have an erroneous test to detect pydantic config map strategies
Issue: https://github.com/hummingbot/hummingbot/issues/5654

**Tests performed by the developer**:
Ran the testcase provided without error

**Tips for QA testing**:

2022-09-12 20:04 UTC, nikspz submitted a review, later dismissed
Test performed:
Cloned and installed feature branch 
Created/Autostart the bot strategies 
Tested the following strategies for the issue:
Pure_MM ok
Avellaneda ok
Perpetual_MM ok
Spot_perp_arb ok
Arbitrage ok
AMM_arb ok
Hedge ok
Liquidity_minning ok
Xemm ok
Fixed_grid ok
Twap ok
Celo ok
Aroon Oscillator ok

2022-09-14 19:26 UTC, cardosofede requested changes

2022-09-14 19:26 UTC, cardosofede commented on bin/hummingbot_quickstart.py
> +            if hasattr(strategy_config, 'hb_config') and issubclass(type(strategy_config.hb_config), BaseStrategyConfigMap)
I think that is better just to check if isinstance(strategy_config, ClientConfigAdapter)

2022-09-19 08:45 UTC, cardosofede approved these changes
LGTM!

2022-09-19 08:46 UTC, merged