refactor/support sushiswap on polygon chain
hummingbot/hummingbot pull request #5727
Opened 2022-09-22 13:07 UTC by gzliudan

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Support sushiswap on polygon and mumbai chain

**Tests performed by the developer**:

sushiswap mumbai buy
```shell
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/price" -d '{
    "connector": "sushiswap",
    "chain": "polygon",
    "network": "mumbai",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "BUY"
}' | jq
```
![1663850804641](https://user-images.githubusercontent.com/7695325/191750790-3cb6113a-0a5d-475a-98c7-b38c13d74d17.png)

sushiswap mumbai sell
```shell
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/price" -d '{
    "connector": "sushiswap",
    "chain": "polygon",
    "network": "mumbai",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "SELL"
}' | jq
```
![1663850869366](https://user-images.githubusercontent.com/7695325/191751022-d2f16ceb-b564-4030-93b2-d1ebe9a9940b.png)

mumbai sushiswap buy
```shell
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/trade" -d '{
    "address": "'"$ETH_ADDRESS"'",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "BUY",
    "chain": "polygon",
    "network": "mumbai",
    "connector": "sushiswap"
}' | jq
```
![1663850947150](https://user-images.githubusercontent.com/7695325/191751299-3f6660a9-63f4-4194-b01a-585de8ac6a08.png)

mumbai sushiswap sell
```shell
curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "${HEADER}" "${SERVER}/amm/trade" -d '{
    "address": "'"$ETH_ADDRESS"'",
    "base": "WBTC2",
    "quote": "USDC2",
    "amount": "1",
    "side": "SELL",
    "chain": "polygon",
    "network": "mumbai",
    "connector": "sushiswap"
}' | jq
```
![1663851179055](https://user-images.githubusercontent.com/7695325/191752096-156b890d-19b0-4b59-accc-aee067127bcd.png)

gateway connect sushiswap
![image](https://user-images.githubusercontent.com/7695325/191750424-6078e520-9245-43fc-b775-507905517899.png)

**Tips for QA testing**:

The adderss of SushiSwapRouter on [polygon](https://polygonscan.com/address/0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506#writeContract) and [mumbai](https://mumbai.polygonscan.com/address/0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506#writeContract)  is `0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506`.

My test tokens:
| Symbol  | Decimals | Address                                                                                                                                         | 
| :---- | ---: | :------------------------------------------------------------------------------------------------------------------------------------------- |
| WBTC2 |    8 | [0x04597a1486b4F9d8284A4771703C1808D2a29b81](https://mumbai.polygonscan.com/address/0x04597a1486b4F9d8284A4771703C1808D2a29b81#readContract) |
| YFI2  |   18 | [0xa79391e7B2b48a4Eb7F2228ef625a32716eE4E93](https://mumbai.polygonscan.com/address/0xa79391e7B2b48a4Eb7F2228ef625a32716eE4E93#readContract) |
| MKR2  |   18 | [0xc16d215c621bbfd12999c9f456dab44db755ddd5](https://mumbai.polygonscan.com/address/0xc16d215c621bbfd12999c9f456dab44db755ddd5#readContract) |
| AAVE2 |   18 | [0x34006a403f5aba9f247a284e6278fbcb7c00df38](https://mumbai.polygonscan.com/address/0x34006a403f5aba9f247a284e6278fbcb7c00df38#readContract) |
| UNI2  |   18 | [0x0a696e15754f9de196a939fecb8c412812d5881d](https://mumbai.polygonscan.com/address/0x0a696e15754f9de196a939fecb8c412812d5881d#readContract) |
| USDC2 |    6 | [0xb6ae5ac95088f80f43a52f6be2b44906492b0d98](https://mumbai.polygonscan.com/address/0xb6ae5ac95088f80f43a52f6be2b44906492b0d98#readContract) |

Anyone can mint tokens, no quantity limit.

2022-12-16 14:55 UTC, fengtality commented
@gzliudan Sorry for the late reply. We've made some architectural changes to Gateway recently and added BNB Chain support for SushiSwap. Do you want to update this PR for the latest `development` code?

2022-12-16 14:57 UTC, gzliudan commented
Ok, I can update this PR next week.

2022-12-19 05:54 UTC, gzliudan commented
This PR is updated on the latest development branch today.

2022-12-21 14:51 UTC, fengtality requested changes

2022-12-21 14:51 UTC, fengtality commented on gateway/src/chains/polygon/polygon_tokens_mumbai.json
> -      "address": "0x9c3c9283d3e44854697cd22d3faa240cfb032889",
Please remove the changes to addresses unless changes are really needed. This prevents potential security issues -thanks

2022-12-21 14:51 UTC, fengtality commented on gateway/src/chains/polygon/polygon_tokens_mumbai.json
> +      "address": "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa",
same as above

2022-12-21 14:51 UTC, fengtality commented on gateway/test/chains/polygon/quickswap/quickswap.test.ts
> -  '0x9c3c9283d3e44854697cd22d3faa240cfb032889',
same as above

2022-12-21 14:51 UTC, fengtality commented on gateway/src/templates/sushiswap.yml
> +      sushiswapRouterAddress: '0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506'
same as above

2022-12-21 14:51 UTC, fengtality commented on gateway/test/chains/polygon/quickswap/quickswap.test.ts
> +  '0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa',
same as above

2022-12-21 15:31 UTC, gzliudan commented
@fengtality @rapcmia OK, the files gateway/test/chains/polygon/quickswap/quickswap.test.ts and gateway/src/chains/polygon/polygon_tokens_mumbai.json are retained unchanged now.

2022-12-22 07:40 UTC, rapcmia commented
PR update:
- Setup source client and gateway successfully
- Tested on mainnet and connected wallet successfully
- Balance display correctly and connector-tokens parameter works as expected 
- Setup simple amm arb
   - Setup config with sushiswap-polygon mainnet and paper_trade connector 
   - Approval success and markets are ready displayed
   - Profitability for no arbitrage displays correctly
   - Difference between the prices of `status` and exchange swap price is close enough
- Build docker image for client and gateway for local build tests
   - Tested on mumbai testnet using WMATIC-DAI
   - Same results achieved as source build 👍 
- Test endpoint:
   - port, wallet and balance check: ok 
   - approval, prices and trade: ok 

Note: _There are noticeable issues on polygon chain on tx execution and not related to this PR_

Pending:
Currently running long term for test for 3-5hrs

2022-12-26 00:17 UTC, rapcmia commented
PR good to be approved however would need pass the GitHub CI:
![image](https://user-images.githubusercontent.com/73840223/209485537-12a75af4-f71c-41f8-bee3-fdfb8a8aa227.png)

2023-01-06 09:47 UTC, rapcmia commented
Hi @gzliudan good day to you
We have not received any response from the previous comment, just checking if you can provide us a timeframe of a possible new commit? PR is good to be approve but getting failed GitHub Ci due to not enough coverages:
![image](https://user-images.githubusercontent.com/73840223/210975348-4860534b-788e-4ca7-a678-ed0dc2a141ae.png)

2023-01-06 09:58 UTC, gzliudan commented
@rapcmia I have no experence on TypeScript, so I can modify some codes, but have no ability to write test codes.

2023-02-10 08:33 UTC, rapcmia commented
Hi @gzliudan good day to you
This PR has been selected as one of top 5 to be added to the next release `1.13.0` from this [poll](https://snapshot.org/#/hbot.eth/proposal/0x5e023da8e21855ec4bb34fcbc124513831b93668a10f788a7d965e71a7b67d28). Please also be advised that we have changes on gateway which is now moved to a new [repository](https://github.com/hummingbot/gateway). At the moment the PR needs to be updated base on the recent changes, current does not display any for polygon / mumbai support for sushiswap

![image](https://user-images.githubusercontent.com/73840223/218041919-a7ba6dbe-7159-471c-928c-0d84546385da.png)

2023-02-10 08:36 UTC, gzliudan commented
I will submit a new PR to gateway [repository](https://github.com/hummingbot/gateway) next week.

> Hi @gzliudan good day to you This PR has been selected as one of top 5 to be added to the next release `1.13.0` from this [poll](https://snapshot.org/#/hbot.eth/proposal/0x5e023da8e21855ec4bb34fcbc124513831b93668a10f788a7d965e71a7b67d28). Please also be advised that we have changes on gateway which is now moved to a new [repository](https://github.com/hummingbot/gateway). At the moment the PR needs to be updated base on the recent changes, current does not display any for polygon / mumbai support for sushiswap
> 
> ![image](https://user-images.githubusercontent.com/73840223/218041919-a7ba6dbe-7159-471c-928c-0d84546385da.png)

2023-02-14 10:31 UTC, gzliudan commented
@rapcmia  Done: https://github.com/hummingbot/gateway/pull/16

2023-02-15 18:35 UTC, closed without merging