Feat/binance perpetual derivative
hummingbot/hummingbot pull request #5976
Opened 2022-12-22 11:34 UTC by yancong001

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR create Binance connector to the latest standards.

**Tests performed by the developer**:

* Test cases for the new code

**Tips for QA testing**:
Normal QA test for Perpetuals connectors.

2022-12-23 10:37 UTC, nikspz commented
Test performed: 
- Cloned and installed feature branch
- Manually created docker image successfully
- Started the client
 - Connected the connector API keys = OK
 - Balance output = OK
 - Create/Import/Start a strategy = OK
 - Check status and status --live match with exchange = OK
 - Order cancellation = OK
 - Ticket and Order book --live match with exchange = OK
 - Order filled events = OK
 - Vertify fee calculation = OK
 - Data collected by datadog = OK
 - Test different token pairs = OK
 - Position retrieval = OK
 
 Pending tests:
 - Funding payment handling
 - Overnight test, checking issues during the longrun:
    - Network reconnection, Order failed submit, Unexpected errors or Warnings

2022-12-26 10:06 UTC, nikspz commented
Hi, @yancong001. Could you please check failing tests?

2022-12-26 10:20 UTC, yancong001 commented
> Hi, @yancong001. Could you please check failing tests?

Of course, but what are the failed tests?

2022-12-26 11:53 UTC, nikspz commented
@yancong001 Please check tests failing here:
https://github.com/hummingbot/hummingbot/actions/runs/3757406022/jobs/6426949434

2022-12-27 07:13 UTC, yancong001 commented
> @yancong001 Please check tests failing here: https://github.com/hummingbot/hummingbot/actions/runs/3757406022/jobs/6426949434

all tests passed

2022-12-27 07:35 UTC, nikspz commented
@yancong001 That’s great, longrun tests left, upon checking should be good. 
Then going to review from our devs.

2023-01-03 22:07 UTC, cardosofede requested changes
The overall is okey, but the idea of this refactor is to adapt the code to the latest standards. Good job, and after this changes I will do the last review and we are ready to merge the PR!

2023-01-03 22:07 UTC, cardosofede commented on hummingbot/connector/derivative/binance_perpetual/binance_perpetual_user_stream_data_source.py
>          self._last_listen_key_ping_ts = None
Same here, you should be using the listen for user stream of the super class

2023-01-04 11:30 UTC, yancong001 commented
> The overall is okey, but the idea of this refactor is to adapt the code to the latest standards. Good job, and after this changes I will do the last review and we are ready to merge the PR!
Ok, I will recheck and revise it soon

2023-01-04 11:30 UTC, yancong001 commented
> The overall is okey, but the idea of this refactor is to adapt the code to the latest standards. Good job, and after this changes I will do the last review and we are ready to merge the PR!

Ok, I will recheck and revise it soon

2023-01-05 13:52 UTC, yancong001 commented
those changes have been updated. @cardosofede

2023-01-06 17:13 UTC, cardosofede commented
Seems like you made all the requested changes, good job!

I have this issue when trying to change the leverage: OSError: Error executing request POST /leverage. HTTP status is 503. Error: {"timestamp":1673025015923,"path":"/fapi/v1/leverage","msg":"Unknown error, please check your request or try again later."}
2023-01-06 14:10:16,406 - 2925 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error executing request POST /leverage. HTTP status is 503. Error: {"timestamp":1673025016447,"path":"/fapi/v1/leverage","msg":"Unknown error, please check your request or try again later."}
Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
    success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 733, in _set_trading_pair_leverage
    set_leverage = await self._api_request(
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 816, in _api_request
    raise IOError(f"Error executing request {method.name} {path_url}. "
OSError: Error executing request POST /leverage. HTTP status is 503. Error: {"timestamp":1673025016447,"path":"/fapi/v1/leverage","msg":"Unknown error, please check your request or try again later."}
2023-01-06 14:10:16,984 - 2925 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error executing request POST /leverage. HTTP status is 503. Error: {"timestamp":1673025017032,"path":"/fapi/v1/leverage","msg":"Unknown error, please check your request or try again later."}
Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
    success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 733, in _set_trading_pair_leverage
    set_leverage = await self._api_request(
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 816, in _api_request
    raise IOError(f"Error executing request {method.name} {path_url}. "
OSError: Error executing request POST /leverage. HTTP status is 503. Error: {"timestamp":1673025017032,"path":"/fapi/v1/leverage","msg":"Unknown error, please check your request or try again later."}
2023-01-06 14:10:17,716 - 2925 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

2023-01-06 17:50 UTC, cardosofede approved these changes
LGTM! @rapcmia let's test in a long run with the latest changes

2023-01-09 11:12 UTC, nikspz approved these changes
Test performed:

Cloned and installed feature branch
Manually created docker image successfully
Started the client
Connected the connector API keys = OK
Balance output = OK
Create/Import/Start a strategy = OK
Check status and status --live match with exchange = OK
Order cancellation = OK
Ticket and Order book --live match with exchange = OK
Order filled events = OK
Vertify fee calculation = OK
Data collected by datadog = OK
Test different token pairs = OK
Position retrieval = OK
Funding payment handling = OK
Overnight test, no issues during the longrun:
no issues on Network reconnection, Order failed, Unexpected errors or Warnings

2023-01-10 02:33 UTC, merged

2023-01-10 02:33 UTC, rapcmia commented
Merged PR in behalf of foundation team. The updated binance perpetual will be applied on the development branch and the next Hummingbot version 1.12.0