Feat/approve tokens changes
hummingbot/hummingbot pull request #6005
Opened 2023-01-11 15:02 UTC by Faouzijedidi1

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2023-01-11 17:53 UTC, cardosofede commented on setup.py
> +    version = "20221221"
why the version is different?

2023-01-11 18:05 UTC, cardosofede requested changes
check those observations!

2023-01-16 16:20 UTC, rapcmia approved these changes
LGTM 

- Installation source/docker, ok 
- Setup simple pancakeswap-bsc on source 
- Test with tokens that needs to be approved
	- Confirmed tokens needs to be enabled on connector
	- Run `gateway approve-token [connector] [token]`
		- Displayed `Token XXXX approval tx is pending`
		- Displayed `Token XXXX is approved for spending for xxxx for wallet xxxx` on both log and output panel 
	- Successfully approved and amm-arb worked ok 
- Test docker with pangolin-avalanche
	- same test done with source, all ok 
- Displayed help on `gateway approve-token -h`
- Test invalid tokens, getting expected error for unsupported tokens 
- Execute `gateway approve-token` while AMM-arb is running, successfully reproduce `Tokens [token] is not approved for spending. Please use manual approval.`

2023-01-17 20:33 UTC, cardosofede approved these changes
LGTM!

2023-01-17 20:33 UTC, merged