fix / docker update script
hummingbot/hummingbot pull request #6090
Opened 2023-02-16 12:17 UTC by rapcmia

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Modified `update.sh` script based on new changes on `create.sh`

**Tests performed by the developer**:
n/a

**Tips for QA testing**:
1. Run create.sh script and use development branch
2. Run update.sh script and use development branch

2023-02-17 09:42 UTC, nikspz approved these changes
Was able to successfully use update.sh script on this one

2023-02-17 15:08 UTC, cardosofede requested changes

2023-02-17 15:08 UTC, cardosofede commented on installation/docker-commands/update.sh
> +   --mount "type=bind,source=${FOLDERS[$j]}/pmm-scripts,destination=/pmm-scripts/" \
review the start.sh script, we changed the mounts for volumes and also we removed the environment variables. Copy the structure of start.sh and we are ready to go!

2023-02-20 13:49 UTC, nikspz approved these changes

2023-02-20 20:11 UTC, cardosofede approved these changes
LGTM!

2023-02-20 20:11 UTC, merged