(fix) binance perpetual position trading_pair
hummingbot/hummingbot pull request #6126
Opened 2023-03-03 04:10 UTC by yancong001

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

* Small fixes for issues in binance _perpetual_derivative found where position used exchange trading pair not hb_trading_pair

**Tests performed by the developer**:
* Ran unit tests

**Tips for QA testing**:

2023-03-06 19:16 UTC, cardosofede requested changes

2023-03-06 19:16 UTC, cardosofede commented on test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_derivative.py
> +            f"Margin Required: 1.614445. Negative PnL assets: {self.symbol}: -1.166074, ."
Check BinancePerpetualDerivative, line 446 and change that on the margin call too.

2023-03-07 04:47 UTC, yancong001 commented on test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_derivative.py
> +            f"Margin Required: 1.614445. Negative PnL assets: {self.symbol}: -1.166074, ."
fixed

2023-03-07 12:22 UTC, nikspz commented
bot flooded with Error messages:
`Could not fetch account updates from Binance_perpetual. Check API key and network connection.`
and 
`Unexpected error while fetching account updates.`
Note: on development branch - no such behavior

Steps to reproduce:
1. Clone and install fix branch
2. Create/start a perpetualMM strategy running binance perpetual (live)
3. Review the log pane

Actual: 
Bot flooded with Could not fetch account updates from Binance_perpetual. Check API key and network connection.

```
2023-03-07 12:07:11,262 - 1069105 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2023-03-07 12:07:11,473 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-03-07 12:07:11,604 - 1069105 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XRP-USDT. 1/1 completed.
2023-03-07 12:07:11,669 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key AW86AJxLUHQhep4pIGBrTatHqhojwwnGJV3tWEWk498ZA2UfigqWwQc4dc2Kkmj4
2023-03-07 12:07:11,882 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2023-03-07 12:07:12,167 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
    hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BTSUSDT'
2023-03-07 12:07:12,168 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
2023-03-07 12:07:12,766 - 1069105 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-03-07 12:07:12,853 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
    hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BTSUSDT'
2023-03-07 12:07:12,853 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
2023-03-07 12:07:13,790 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
    hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BTSUSDT'
2023-03-07 12:07:13,791 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
2023-03-07 12:07:14,599 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
    hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BTSUSDT'
2023-03-07 12:07:14,599 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
2023-03-07 12:07:15,257 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most [...]

2023-03-08 05:26 UTC, yancong001 commented
> bot flooded with Error messages: `Could not fetch account updates from Binance_perpetual. Check API key and network connection.` and `Unexpected error while fetching account updates.` Note: on development branch - no such behavior
> 
> Steps to reproduce:
> 
> 1. Clone and install fix branch
> 2. Create/start a perpetualMM strategy running binance perpetual (live)
> 3. Review the log pane
> 
> Actual: Bot flooded with Could not fetch account updates from Binance_perpetual. Check API key and network connection.
> 
> [6126.zip](https://github.com/hummingbot/hummingbot/files/10909290/6126.zip)
> 
> [logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/10909281/logs_conf_perpetual_market_making_1.log)
> 
> ```
> 2023-03-07 12:07:11,262 - 1069105 - hummingbot.client.hummingbot_application - INFO - start command initiated.
> 2023-03-07 12:07:11,473 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
> 2023-03-07 12:07:11,604 - 1069105 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XRP-USDT. 1/1 completed.
> 2023-03-07 12:07:11,669 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key AW86AJxLUHQhep4pIGBrTatHqhojwwnGJV3tWEWk498ZA2UfigqWwQc4dc2Kkmj4
> 2023-03-07 12:07:11,882 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
> 2023-03-07 12:07:12,167 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
> Traceback (most recent call last):
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
>     await self._status_polling_loop_fetch_updates()
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
>     await safe_gather(
>   File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
>     return await asyncio.gather(*args, **kwargs)
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
>     hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
>     return symbol_map[symbol]
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BTSUSDT'
> 2023-03-07 12:07:12,168 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
> 2023-03-07 12:07:12,766 - 1069105 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
> 2023-03-07 12:07:12,853 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
> Traceback (most recent call last):
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
>     await self._status_polling_loop_fetch_updates()
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
>     await safe_gather(
>   File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
>     return await asyncio.gather(*args, **kwargs)
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
>     hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
>     return symbol_map[symbol]
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BTSUSDT'
> 2023-03-07 12:07:12,853 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
> 2023-03-07 12:07:13,790 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
> Traceback (most recent call last):
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
>     await self._status_polling_loop_fetch_updates()
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
>     await safe_gather(
>   File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
>     return await asyncio.gather(*args, **kwargs)
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
>     hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
>     return symbol_map[symbol]
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BTSUSDT'
> 2023-03-07 12:07:13,791 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Could not fetch account updates from Binance_perpetual. Check API key and network connection.
> 2023-03-07 12:07:14,599 - 1069105 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
> Traceback (most recent call last):
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/exchange_py_base.py", line 804, in _status_polling_loop
>     await self._status_polling_loop_fetch_updates()
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 195, in _status_polling_loop_fetch_updates
>     await safe_gather(
>   File "/home/ubuntu/6126binperfix/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
>     return await asyncio.gather(*args, **kwargs)
>   File "/home/ubuntu/6126binperfix/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 577, in _update_positions
>     hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
>     return symbol_map[symbol]
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BTSUSDT'
> 2023-03-07 12:07:14,599 - 1069105 - hummingbot.connector.derivative.binance_per [...]

2023-03-08 12:03 UTC, nikspz approved these changes
Test performed:

- Clone and installed fix branch
- Created/started longterm bot perpetualMM + binance perpetual
- Reviewed no error/warning messages showed
- Created docker image manually
- Started docker image no issues showed

2023-03-08 18:36 UTC, cardosofede requested changes
we can continue the conversation on private but you should review why we have that key error since when the connector starts all the trading pairs should be initialized.
Also I checked on Binance perpetuals USDM and the Pair BTSUSDT doesn't exist

2023-03-08 18:36 UTC, cardosofede commented on hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py
> +                try:
This is not needed since you should have the full map in the connector. Is not related to initialization

2023-03-08 18:36 UTC, cardosofede commented on hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py
> +                try:
same here

2023-03-10 14:57 UTC, cardosofede approved these changes
LGTM!

2023-03-10 14:57 UTC, merged