add bronze exchanges
hummingbot/hummingbot pull request #6228
Opened 2023-04-13 18:01 UTC by david-hummingbot

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- changed readme to reflect changes in latest polls

https://snapshot.org/#/hbot.eth/proposal/0xc130b4466d90ebf68da68b26c1e800678e358f81dc142ae888546e44c227d655
https://snapshot.org/#/hbot.eth/proposal/0xb4ad7e28f398ff028fa02d5ba15c7eccddd54e4b418877aeab5b3a82f7214e5d

- add bronze exchanges to readme

**Tests performed by the developer**:

**Tips for QA testing**:

2023-04-14 06:16 UTC, rapcmia approved these changes

2023-04-14 06:24 UTC, rapcmia approved these changes

2023-04-14 13:28 UTC, fengtality requested changes
* For each exchange, change the links to the Hummingbot documentation page, rather than the exchange website
* Please add entries for Hotbit and Bit.com to this list as Bronze connectors
* Capitalize `xswap`

2023-04-16 22:59 UTC, fengtality approved these changes

2023-04-16 22:59 UTC, merged