Ascendex - add market and limit order type
hummingbot/hummingbot pull request #6357
Opened 2023-06-02 04:54 UTC by spazeba

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Based on the Technical Roadmap, Ascendex need to support all order types.
This PR will allow sending MARKET&LIMIT_MAKER orders with Ascendex.

**Tests performed by the developer**:

**Tips for QA testing**:

2023-06-02 07:36 UTC, rapcmia commented
PR update:
- Ran test on PMM and AMM-arb (CEX connectors) all ok

Pending:
- Looking for scripts to use to test the added market and limit_maker. Current having issues with `invalid_price`

2023-06-05 16:13 UTC, cardosofede requested changes
Hey @spazeba, these changes are OK but you are missing the changes in the method _place_order. Check that you need to construct the params that you are going to send for the order type market and you don't need to send the price in this case.
You can use as a reference this PR: #6279

2023-06-07 10:43 UTC, rapcmia commented
Hi @spazeba tried run the github checks twice but getting same error. can you possibly have a look? thanks

2023-06-08 13:52 UTC, rapcmia commented
Hi @spazeba thanks for the update,
Please also be advised that this bounty will be part of our upcoming version `1.17.0` so we'd like to have it review and working by the end of this week. Please let us now if this can be done else we can open the bounty again. Thank you!

2023-06-13 20:06 UTC, nikspz commented
Test performed:
- Clone and install feature branch
- Checked bot could place limit order on ascendex
- Ran market order script on ascendex, bot returns an error:

[market_orders_test_ascendex.txt](https://github.com/hummingbot/hummingbot/files/11738759/market_orders_test_ascendex.txt)


[logs_market_orders_test_ascendex2.log](https://github.com/hummingbot/hummingbot/files/11738834/logs_market_orders_test_ascendex2.log)

```
2023-06-13 20:02:01,132 - 804597 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange.AscendExExchange - NETWORK - Error submitting buy MARKET order to Ascend_ex for 0.004 ETH-USDT NaN.
Traceback (most recent call last):
  File "/home/ubuntu/ascendx/hummingbot/connector/exchange_py_base.py", line 480, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/ubuntu/ascendx/hummingbot/connector/exchange_py_base.py", line 498, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/ubuntu/ascendx/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 252, in _place_order
    int(exchange_order["data"]["info"]["timestamp"]) * 1e-3,
KeyError: 'timestamp'
2023-06-13 20:02:01,133 - 804597 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange.AscendExExchange - WARNING - Failed to submit BUY order to Ascend_ex. Check API key and network connection.
2023-06-13 20:02:01,137 - 804597 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1686686521.0, "order_id": "HMBotBEHUTd988dba58583", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "ascend_ex"}
2023-06-13 20:02:01,138 - 804597 - hummingbot.connector.client_order_tracker - INFO - Order HMBotBEHUTd988dba58583 has failed. Order Update: OrderUpdate(trading_pair='ETH-USDT', update_timestamp=1686686521.0, new_state=<OrderState.FAILED: 6>, client_order_id='HMBotBEHUTd988dba58583', exchange_order_id=None, misc_updates=None)
```

![image](https://github.com/hummingbot/hummingbot/assets/83953535/25da16b0-b6bf-4a26-a36f-0ce806d8a3fc)

2023-06-13 20:15 UTC, spazeba commented
hi @rapcmia @nikspz, I tried to fixed _place_order, now I think need to do changes similar to PR https://github.com/hummingbot/hummingbot/pull/6372 (related to timestamp)

2023-06-19 08:50 UTC, spazeba commented
I think the issue in that current ascendex timestamp need to be int, but `market orders script still fails with KeyError: 'timestamp'`  on my code attempts. So could't solve it currently. 
Also if you will check this PR https://github.com/hummingbot/hummingbot/pull/6372/files changes, comparing to it ascendex do not have TimeInForce `poc` (https://ascendex.github.io/ascendex-pro-api/#place-order)

2023-06-22 06:49 UTC, closed without merging