Feat/market data collector
hummingbot/hummingbot pull request #6364
Opened 2023-06-06 20:30 UTC by cardosofede

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds the functionality to collect market data in the background from the markets that are initialized in the strategy that is running.
Market Data Collection is a new config variable in the conf_client. You can change the following things:
- Enabled: True/False --> True
- Interval: seconds to collect data --> 60
- Depth: levels of the order book to collect --> 20

The data collected is:
- Exchange
- Trading Pair
- Timestamp
- Mid Price
- Best Ask
- Best Bid
- Order Book

**Tests performed by the developer**:
Run a strategy with:
- 1 market
- 3 markets
Check the data in the new table called MarketData
<img width="1611" alt="image" src="https://github.com/hummingbot/hummingbot/assets/36869960/9a02ff0a-1f8f-4677-8a5c-7d27dba7a60e">

**Tips for QA testing**:
- Run strategy and check that the new table is created.
- Check a strategy that works with DEXes and see if there is an issue here. I suspect that can be something since the price type mid-price is not implemented there.
TIP: you have to remove the conf_client.yml file because there is a new conf.

2023-06-07 22:41 UTC, fengtality reviewed
LGTM

Is it possible to add a column to `MarketData` to store trades that have occurred during the past `interval`?

2023-06-07 22:41 UTC, fengtality approved these changes

2023-06-07 23:00 UTC, fengtality requested changes
actually, i think you should add a param `market_data_collection_logging_enabled`. If this param is true, print a log statement stating that market data has been recorded and the timestamp. This will help users track if data is being recorded.

2023-06-08 06:47 UTC, rapcmia commented
PR update:
- Test on local WSL (Ubuntu20.04lts) source env
- Test latest commit `5580450a90a499607c2536dbb87faa2cb8ad5c4a`
- Test error validations for new params, all ok 💯 
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/a34554a2-e815-44d8-9828-7a34ab1be925)
- Setup tests using `paper_trade {binance, kucoin}` 
- Check SQlite:
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/ed684fa2-81f5-4581-a273-d8e4f54d44d6)
   - Compare from `development` and confirm table `MarketData` is available on this PR
     ![image](https://github.com/hummingbot/hummingbot/assets/73840223/e9e15d52-ba22-4182-b945-108f08096ab8)
      - Check table records and compare timestamps on logs
      - Starts recording at the set value of `market_data_collection_interval` ✅
   - Test on PMM and XEMM strategy (CEX/CEX)
      - Compare data on different markets, all ok 

Pending:
- AMM-ARB and DEX connectors
- Docker env

2023-06-08 08:58 UTC, cardosofede commented
> LGTM
> 
> 
> 
> Is it possible to add a column to `MarketData` to store trades that have occurred during the past `interval`?

This can be really interesting, but probably will be better to create another table and store the raw trades to make the access easier. Let's discuss in our internal dev call about this

2023-06-08 10:33 UTC, nikspz commented
- Market data enabled configuration:
    - no autocomplete variants by TAB button (True/False)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/c7ac081f-76ca-4c78-a005-d9dab1b9b108)
- Yes/No y/n True/False works (changed to True/False)
- source when Market data collection disabled not recorded data ✅
![image](https://github.com/hummingbot/hummingbot/assets/83953535/117c7652-14a6-48a6-b836-d76dcba926bd)
- source pureMM
    - MarketData recorded
- source amm_arb
    - MarketData is empty ❌
![image](https://github.com/hummingbot/hummingbot/assets/83953535/b35491d4-5eb0-4640-bdc7-990a101eeafb)

- source binance perpetualMM
    - MarketData recorded
- docker binance pureMM:
    - MarketData recorded
- docker + docker gw amm_arb Uniswap Arbitrum_one
    ran for ~5 min
    - MarketData is empty ❌
- docker + docker gw amm_arb Quickswap polygon
ran for ~5 min
- MarketData is empty ❌

2023-06-08 12:29 UTC, rapcmia approved these changes
Test summary:
- Setup on source / docker ok 
- Ran tests on local mbp, wsl and AWS instance 
- Compare PR to development branch ok 
- Test with live and paper_trade connectors
- Check new added params for `market_data_collection` all ok 
- Overview on added table on sqlite `MarketData`
- Check table records and compare timestamps on logs 
- Start recording data at the set value of `market_data_collection_interval`
    - Different markets with separate data are recorded
    - Does not record when `market_data_collection_enabled` is false
- Ran test PMM and XEMM for CEX connectors :ok 
- Ran tests on AMM and CLOB connectors
    - AMM-arb: `MarketData` table is empty 
    - CLOB connectors (dexalot/Injective): marketData recorded

Note:
    - Initially deleted `../conf/conf_client` and launch the client, all ok 
    - There is no autocoplete selection for `market_data_collection_enabled` on UI

2023-06-10 15:33 UTC, fengtality approved these changes

2023-06-10 15:33 UTC, merged