update docker_build_tags.yml
hummingbot/hummingbot pull request #6411
Opened 2023-06-26 19:18 UTC by david-hummingbot

- workflow is adding an extra "v" to the version tag

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2023-06-26 20:41 UTC, fengtality requested changes

2023-06-26 20:41 UTC, fengtality commented on .github/workflows/docker_build_tags.yml
> +        run: echo ::set-output name=VERSION::version-${GITHUB_REF#refs/tags/v}
looks like there might be an an extra `v` at the end

2023-06-27 02:04 UTC, cardosofede approved these changes
@fengtality @david-hummingbot I approve the changes based on the last comment that David did. Needs last check of Mike to merge

2023-06-27 18:07 UTC, fengtality approved these changes

2023-06-27 18:07 UTC, merged