(Clean-up) balances and allowances display
hummingbot/hummingbot pull request #6787
Opened 2024-01-17 02:01 UTC by isreallee82

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Addittion of a new gateway balance command that reports balance and allowance  for single connected wallets.
Adds allowance to balance display
Reafctor of all the necessary function to make the command work.
Fix other related bugs.

Tests performed by the developer:

Tips for QA testing:

2024-01-18 15:04 UTC, nikspz commented
Initial tests:

Cloned and installed PR6787 and gateway latest development

1) gateway balance showing 0 balance for dexalot (when other 4 exchanges connected as well), however dexalot balance showing when using `gateway balance dexalot_avalanche_dexalot` command

![gateway balance showing 0 balance for dexalot](https://github.com/hummingbot/hummingbot/assets/83953535/85731215-b8ee-4ba5-b9f2-7cd89b35da14)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/d7c986f6-20cf-4e60-bb4a-efaeb8ed9adb)

2) Allowances for uniswap_ethereum_goerli and uniswap_ethereum_arbitrum showing huge numbers, seems expected on allowances showed the same

![image](https://github.com/hummingbot/hummingbot/assets/83953535/e10c2f0d-e371-4e75-869f-654227b95b26)


![image](https://github.com/hummingbot/hummingbot/assets/83953535/9c439260-9e90-40ad-a957-9ed4191712b0)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/183e7c03-653c-499f-a447-bb3c31817ddb)

2024-01-18 17:59 UTC, isreallee82 commented
fixed the dexalot error display to return 0 value also on single exchange request if not connected, As for the allowances with huge amount, I am sure that was expected since the bot is designed to approve them @nikspz

2024-01-19 14:07 UTC, nikspz commented
@isreallee82 currently the same issue for dexalot

Steps: 
1. Clone and install PR6787 commit 1abea4a and gateway latest development
2. gateway connect dexalot_avalanche
3. check gateway balance or gateway balance dexalot

Actual:
showing 0 balance for dexalot


![gateway balance showing 0 balance for dexalot](https://github.com/hummingbot/hummingbot/assets/83953535/2690bb2e-9eef-4438-b41c-3c72962fa934)

2024-01-19 22:13 UTC, isreallee82 commented
sorry for late response @nikspz  As mentioned earlier, I've configured the display to return a default value of 0 for any exchange that doesnt use allowance since dexalot is a club spot, as evidenced in the gateway request terminal. also configured to match the index since balances and allowances are pulled from exchanges on the gateway conference file

2024-01-20 01:52 UTC, fengtality requested changes

2024-01-20 01:52 UTC, fengtality commented on hummingbot/client/command/gateway_command.py
> +                        "Allowance": allowance,
For display purposes, I suggest showing "999999+" if `allowance > 999999`. This should address @nikspz's comment.

2024-01-20 02:56 UTC, isreallee82 commented
noted @nikspz @fengtality I will refactor, test and push asap.

2024-01-22 14:25 UTC, nikspz commented
@isreallee82 

commit 1b8bf44 issue for dexalot

Steps:
Clone and install PR6787 commit 1b8bf44 and gateway latest development
gateway connect dexalot_avalanche
check gateway balance or gateway balance dexalot

Actual:
showing 0 balance for dexalot


![image](https://github.com/hummingbot/hummingbot/assets/83953535/be8e6529-db5a-4264-bb06-c4873d6df640)

Crosschecked, showed on Client+gateway development, but broken on this PR

2024-01-22 22:52 UTC, isreallee82 commented
should work now as expected @nikspz

2024-03-08 23:57 UTC, fengtality commented
@isreallee82 Sorry for the delay in reviewing this PR. Everything looks good except for this issue I found where the connector filter doesn't seem to work. In the examples below, it only displays the first item rather than the selected conenctor.
<img width="451" alt="Screenshot 2024-03-08 at 3 54 17 PM" src="https://github.com/hummingbot/hummingbot/assets/1795030/0e300c0c-aeba-441b-85d5-d6d4d44f33fa">

2024-03-10 15:18 UTC, isreallee82 commented
Ohh it’s fine @fengtality i will look into that and make a push asap

2024-03-10 16:54 UTC, isreallee82 commented
fix that @fengtality

2024-03-15 13:30 UTC, nikspz approved these changes
Test performed:

- Re-check connectors based `gateway balance` with allowances ✔
- Review gateway balance now shows balances for separate connectors and shows correct walelts ✔
- command connector-tokens works (added tokens to balance)✔
- Review allowances showing 999+ for big numbers now ✔
- Created/started amm_arb strategy succesfully for tokens with allowances ✔

Note: Review delay for checking single gateway balance could up to ~7-8sec 📈
Note: Review gateway balance for too many connectors returns Timeout Error ❌(reproduced on development earlier)



Checking gateway balance for single connector with allowances takes ~7-8 seconds: 
![checking balance with allowances is too slow](https://github.com/hummingbot/hummingbot/assets/83953535/03daa92e-6254-45b3-938d-907dc76138e7)

Checking gateway balance for multiple connectors takes time (if too many connectors command will crash with Timeout Error)

![multiple connectors checking balance with allowances is too slow ](https://github.com/hummingbot/hummingbot/assets/83953535/1b266072-743c-40bd-8290-f6dbf0721250)

2024-03-30 03:43 UTC, fengtality approved these changes
LGTM

2024-03-30 03:43 UTC, merged