(feat) executors_improvements
hummingbot/hummingbot pull request #7316
Opened 2024-11-27 19:24 UTC by cardosofede

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2024-11-27 22:16 UTC, fengtality requested changes
Getting error
```
2024-11-27 14:12:53,160 - 82269 - hummingbot.strategy_v2.executors.arbitrage_executor.arbitrage_executor - ERROR - Error calculating profitability: 'ArbitrageExecutorConfig' object has no attribute 'gas_conversion_price'
```

2024-11-27 22:52 UTC, fengtality submitted a review, later dismissed
I think you should clean up the way that fees are calculated in the lines of `arbitrage_executor.py` below:
```
gas_cost = connector.network_transaction_fee
return gas_cost.amount * self.config.gas_conversion_price
```

- network transaction fee returned is in native chain asset, ie ETH
- allow user to define a `gas_token_quote_price` field = 3300
- gas cost = base/quote price * `gas_token_quote_price` * gas_cost.amount

2024-12-04 19:01 UTC, nikspz commented
commit f3ed3a7

Failed to start generic.grid_strike_grid_component using hyperliquid

Steps:
1. Clone and install PR7316
2. create controller config with ` create --controller-config generic.grid_strike_grid_component` using hyperliquid (spot) and HYPE-USDC pair
3. create script config `create --script-config v2_with_controllers`
4. start 

Actual:
ERROR - OrderCandidate.__init__() missing 1 required positional argument: 'order_side'



[hpl2.zip](https://github.com/user-attachments/files/18012756/hpl2.zip)
[logs_hpl2.log](https://github.com/user-attachments/files/18013043/logs_hpl2.log)


```
2024-12-04 18:38:10,574 - 17930 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - OrderCandidate.__init__() missing 1 required positional argument: 'order_side'
Traceback (most recent call last):
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
    await self.control_task()
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/executors/grid_executor/grid_executor.py", line 201, in control_task
    self.adjust_and_place_open_order(level)
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/executors/grid_executor/grid_executor.py", line 301, in adjust_and_place_open_order
    order_candidate = self._get_open_order_candidate(level)
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/executors/grid_executor/grid_executor.py", line 352, in _get_open_order_candidate
    return OrderCandidate(
TypeError: OrderCandidate.__init__() missing 1 required positional argument: 'order_side'
```
![image](https://github.com/user-attachments/assets/9009accd-a3d8-4525-8b86-e5df674c4a2d)

2024-12-10 14:51 UTC, rapcmia commented
PR update:
- Setup config based on shared .yml file from dev team
 - Change `open_order_type` since it only able to use {1,2,3}
    ```
    2024-12-06 06:01:34,319 - 3073001 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 1 validation error for GridStrikeConfig
    triple_barrier_config -> open_order_type
      value is not a valid enumeration member; permitted: 1, 2, 3 (type=type_error.enum; enum_values=[<OrderType.MARKET: 1>, <OrderType.LIMIT: 2>, <OrderType.LIMIT_MAKER: 3>])
    Traceback (most recent call last):
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/client/command/start_command.py", line 125, in start_check
        self._initialize_strategy(self.strategy_name)
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/client/command/start_command.py", line 271, in _initialize_strategy
        self.start_script_strategy()
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/client/command/start_command.py", line 191, in start_script_strategy
        script_strategy, config = self.load_script_class()
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/client/command/start_command.py", line 227, in load_script_class
        script_class.init_markets(config)
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 188, in init_markets
        controllers_configs = config.load_controller_configs()
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 112, in load_controller_configs
        loaded_configs.append(config_class(**config_data))
      File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    pydantic.error_wrappers.ValidationError: 1 validation error for GridStrikeConfig
    triple_barrier_config -> open_order_type
      value is not a valid enumeration member; permitted: 1, 2, 3 (type=type_error.enum; enum_values=[<OrderType.MARKET: 1>, <OrderType.LIMIT: 2>, <OrderType.LIMIT_MAKER: 3>])
    ```
     - Config updated base on test preference and change from 5 to 2 ✅ 

---

Run the modified `grid_strike_grid_component` for `3d 13hours` on VPS
![image](https://github.com/user-attachments/assets/8234aac7-7fb3-42e0-8377-a31fe6700a41)
![image](https://github.com/user-attachments/assets/d43725db-9d3b-441c-a4d2-ac6d11fc29e4)
![image](https://github.com/user-attachments/assets/f6c4a447-d52c-41e9-b5c6-3bcaf0473235)

---

When placing take_profit there are instances of `OSError...Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history`
  ```
  2024-12-06 07:17:52,147 - 3079705 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Error submitting sell LIMIT_MAKER order to Binance_perpetual for 3280 TROY-USDT 0.0045360.
  Traceback (most recent call last):
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
      await self._place_order_and_process_update(order=order, **kwargs,)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
      exchange_order_id, update_timestamp = await self._place_order(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 265, in _place_order
      order_result = await self._api_post(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 867, in _api_post
      return await self._api_request(*args, **kwargs)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
      request_result = await rest_assistant.execute_request(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
      response = await self.execute_request_and_get_response(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
      raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
  OSError: Error executing request POST https://fapi.binance.com/fapi/v1/order. HTTP status is 400. Error: {"code":-5022,"msg":"Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history"}
  2024-12-06 07:17:52,149 - 3079705 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - WARNING - Failed to submit SELL order to Binance_perpetual. Check API key and network connection.
  2024-12-06 07:17:52,153 - 3079705 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733469472.0, "order_id": "x-nbQe1H39STYUT62894d016769c1f17", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "binance_perpetual"}
  2024-12-06 07:17:52,154 - 3079705 - hummingbot.connector.client_order_tracker - INFO - Order x-nbQe1H39STYUT62894d016769c1f17 has failed. Order Update: OrderUpdate(trading_pair='TROY-USDT', update_timestamp=1733469472.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-nbQe1H39STYUT62894d016769c1f17', exchange_order_id=None, misc_updates=None)
  ```
  - The only LIMIT_MAKER (3) set on my config was `take_profit_order_type`

---

From yesterday (12092024) till today (12102024), observed that it has been stuck on `Unexpected error running clock tick.`
  ```
  2024-12-09 23:40:19,208 - 3079705 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
  Traceback (most recent call last):
    File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
      child_iterator.c_tick(self._current_tick)
    File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
      self.tick(timestamp)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/script_strategy_base.py", line 75, in tick
      self.on_tick()
    File "/home/rapcomia/github/hummingbot/7316/scripts/v2_with_controllers.py", line 83, in on_tick
      super().on_tick()
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 294, in on_tick
      self.executor_orchestrator.execute_action(action)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 104, in execute_action
      self.store_executor(action)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 172, in store_executor
      MarketsRecorder.get_instance().store_or_update_executor(executor)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 205, in store_or_update_executor
      serialized_config = executor.executor_info.json()
    File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
    File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 238, in dumps
      **kw).encode(obj)
    File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
  TypeError: Object of type 'TrackedOrder' is not JSON serializable
  ```
  - Error occurred every tick
  - While this error occurs, observed that the strategy still able to create, cancel limit orders

Steps to r [...]

2024-12-10 17:51 UTC, cardosofede commented
@rapcmia thanks for the feedback, I will do some clarifications for each reported issue so we can add it to the docs at some point @david-hummingbot:
1. the only options available are 1, 2, 3
2. it's the expected behavior in case that we send an order and the ob is updated automatically, I will add an extra parameter to place the order x% from that price.
3. I will research this error since it's a bug

2024-12-11 17:31 UTC, rapcmia commented
PR update for `18c90ac71e5a46c6b1fef98efe5f23cc83a8c25b`
- Recheck config based on meeting with dev team today
- Observed set order frequency (10)
    - Every 10s an order will be created  until reaches a max of 5 orders ✅
    - Every 10s only 1 order created due to set max_order_per_batch ✅
- On this setup, we already changed take_profit_order_type to `limit` orders ✅ 
- Observed positions opened and closed okay
- After 5hours running bot, the previous typeError started again after closing grid orders ❌ 
```
2024-12-11 14:48:06,435 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order x-nbQe1H39SPTUT628ffaf7ecc331bb5 for 13 to CLOSE a PNUT-USDT position at 1.1461400.
2024-12-11 14:48:06,445 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928486.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "13", "price": "1.1461400", "order_id": "x-nbQe1H39SPTUT628ffaf7ecc331bb5", "creation_timestamp": 1733928486.0, "exchange_order_id": "1762240407", "leverage": 30, "position": "CLOSE", "event_name": "SellOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-12-11 14:48:15,486 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT628ffb008da8a1bb5 for 13 to OPEN a PNUT-USDT position at 1.1295700.
2024-12-11 14:48:15,497 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928495.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "13", "price": "1.1295700", "order_id": "x-nbQe1H39BPTUT628ffb008da8a1bb5", "creation_timestamp": 1733928495.0, "exchange_order_id": "1762249208", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-12-11 14:48:25,533 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT628ffb0a23a821bb5 for 13 to OPEN a PNUT-USDT position at 1.1141400.
2024-12-11 14:48:25,546 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928505.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "13", "price": "1.1141400", "order_id": "x-nbQe1H39BPTUT628ffb0a23a821bb5", "creation_timestamp": 1733928505.0, "exchange_order_id": "1762259102", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-12-11 14:48:35,584 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT628ffb13bbbe51bb5 for 13 to OPEN a PNUT-USDT position at 1.0987100.
2024-12-11 14:48:35,597 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928515.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "13", "price": "1.0987100", "order_id": "x-nbQe1H39BPTUT628ffb13bbbe51bb5", "creation_timestamp": 1733928515.0, "exchange_order_id": "1762269138", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-12-11 14:48:45,642 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT628ffb1d529ce1bb5 for 13 to OPEN a PNUT-USDT position at 1.0832800.
2024-12-11 14:48:45,660 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928525.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "13", "price": "1.0832800", "order_id": "x-nbQe1H39BPTUT628ffb1d529ce1bb5", "creation_timestamp": 1733928525.0, "exchange_order_id": "1762279390", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-12-11 14:48:55,717 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT628ffb26e997d1bb5 for 13 to OPEN a PNUT-USDT position at 1.0678500.
... trimmed

2024-12-11 14:49:56,984 - 3508311 - hummingbot.strategy.script_strategy_base - INFO - (PNUT-USDT) Canceling the limit order x-nbQe1H39BPTUT628ffb26e997d1bb5. [clock=2024-12-11 14:49:56+00:00]
2024-12-11 14:49:56,985 - 3508311 - hummingbot.strategy.script_strategy_base - INFO - (PNUT-USDT) Canceling the limit order x-nbQe1H39BPTUT628ffb1d529ce1bb5. [clock=2024-12-11 14:49:56+00:00]
2024-12-11 14:49:56,985 - 3508311 - hummingbot.strategy.script_strategy_base - INFO - (PNUT-USDT) Canceling the limit order x-nbQe1H39BPTUT628ffb13bbbe51bb5. [clock=2024-12-11 14:49:56+00:00]
2024-12-11 14:49:56,986 - 3508311 - hummingbot.strategy.script_strategy_base - INFO - (PNUT-USDT) Canceling the limit order x-nbQe1H39BPTUT628ffb0a23a821bb5. [clock=2024-12-11 14:49:56+00:00]
2024-12-11 14:49:56,986 - 3508311 - hummingbot.strategy.script_strategy_base - INFO - (PNUT-USDT) Canceling the limit order x-nbQe1H39BPTUT628ffb008da8a1bb5. [clock=2024-12-11 14:49:56+00:00]
2024-12-11 14:49:57,189 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928597.0, "order_id": "x-nbQe1H39BPTUT628ffb26e997d1bb5", "exchange_order_id": "1762287045", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-12-11 14:49:57,189 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-nbQe1H39BPTUT628ffb26e997d1bb5.
2024-12-11 14:49:57,295 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928597.0, "order_id": "x-nbQe1H39BPTUT628ffb0a23a821bb5", "exchange_order_id": "1762259102", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-12-11 14:49:57,295 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-nbQe1H39BPTUT628ffb0a23a821bb5.
2024-12-11 14:49:57,308 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928597.0, "order_id": "x-nbQe1H39BPTUT628ffb008da8a1bb5", "exchange_order_id": "1762249208", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-12-11 14:49:57,309 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-nbQe1H39BPTUT628ffb008da8a1bb5.
2024-12-11 14:49:57,317 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928597.0, "order_id": "x-nbQe1H39BPTUT628ffb1d529ce1bb5", "exchange_order_id": "1762279390", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-12-11 14:49:57,318 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-nbQe1H39BPTUT628ffb1d529ce1bb5.
2024-12-11 14:49:57,326 - 3508311 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733928597.0, "order_id": "x-nbQe1H39BPTUT628ffb13bbbe51bb5", "exchange_order_id": "1762269138", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-12-11 14:49:57,327 - 3508311 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-nbQe1H39BPTUT628ffb13bbbe51bb5.
2024-12-11 14:49:59,000 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:00,001 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:01,023 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:02,034 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:03,036 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:04,038 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Grid is already expired by CloseType.TAKE_PROFIT.
2024-12-11 14:50:05,046 - 3508311 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERR [...]

2024-12-12 04:49 UTC, rapcmia commented
PR update:
- Import controller and config to deploy ✅ 
- Deploy instance ✅ 
  - Does not place order and stuck on `Grid is already expired by CloseType.TAKE_PROFIT` ❌ 
    ![image](https://github.com/user-attachments/assets/e321d707-6973-4f30-a451-e643250d993f)
     - Crosscheck with hummingbot client and getting same behavior 
     - Tried to delete data folder to check if there is any diff, no go
     - Observed that once you pause from dashboard ( manual cashout for controller xxx )
        - Check `status` and it displays a number of take_profit closeTypes when there was no order placed ❌ 
        - Check executor table all 3 (take_profit)
           ![image](https://github.com/user-attachments/assets/c2fcaa5e-f7cb-4a0a-bdda-44adba6b40a2)

---

Steps to reproduce:
1. Import the controller onto backendapi or deploy `/bots/conf/controller`
2. Import the `grid_strike_grid_component.py` to backendapit or deploy `/bot/controller/generic`
3. Connect binance perpetual API keys then deploy a instance on dashboard
    - Check status of container on terminal ❗ 
    - Check if it will return `Grid is already expired by CloseType.TAKE_PROFIT`
4. Pause the controller from dashboard 
    - Check status of controller on terminal ❗
    - Observed number of closeTypes.TAKE_PROFIT

[hummingbot-gs2-pnuusdt-2024.12.12_12.19.zip](https://github.com/user-attachments/files/18105561/hummingbot-gs2-pnuusdt-2024.12.12_12.19.zip)

2024-12-16 13:50 UTC, rapcmia commented
PR update `91074a1385b659ec0d2574fd09d902983d9747c9`:

Run tests on `grid_strike_grid_component.py`
> Does not place order and stuck on Grid is already expired by CloseType.TAKE_PROFIT ❌

Its now fix and my bots are working as expected:
![image](https://github.com/user-attachments/assets/43fbee59-0ad2-44d7-802e-c7d9b67c6b75)
- Creates orders every 30s with set max batch orders 2 ✅ 
    - Cancels order on the set time_limit ✅ 
- When filled, create orders to close position
    - When reaching set time_limit for close orders, created market order with the total order size and close the position successfully ✅ 
 
> From yesterday (12092024) till today (12102024), observed that it has been stuck on Unexpected error running clock tick.

I'm not getting any of the prev reported error but will leave another day of running before we conclude test is okay
- `todo`: Will update tomorrow for status of running bot 

---

Run test on `arbitrage_controller.py`

![image](https://github.com/user-attachments/assets/3854cc8b-edf0-4129-b8cd-95e04e3db427)
- Setup a bot with okx and dexalot using AVAX as base and USDC/USDC on quote
- Start the bot however returns a number of errors
    - Getting `Error updating executors info` ❌ 
      ```
      2024-12-16 13:05:24,285 - 3223087 - hummingbot.strategy.script_strategy_base - ERROR - Error updating executors info: 'NoneType' object has no attribute 'executed_amount_base'
      Traceback (most recent call last):
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 266, in update_executors_info
          self.executors_info = self.executor_orchestrator.get_executors_report()
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in get_executors_report
          report[controller_id] = [executor.executor_info for executor in executors_list if executor]
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in <listcomp>
          report[controller_id] = [executor.executor_info for executor in executors_list if executor]
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
          net_pnl_pct=self.net_pnl_pct,
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
          return self.get_net_pnl_pct()
        File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 110, in get_net_pnl_pct
          return self.net_pnl_quote / self.buy_order.order.executed_amount_base
      AttributeError: 'NoneType' object has no attribute 'executed_amount_base'
      ```
  - Getting `Unexpected  error running clock tick` ❌ 
    ```
    2024-12-16 13:05:24,300 - 3223087 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
    Traceback (most recent call last):
      File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
        child_iterator.c_tick(self._current_tick)
      File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
        self.tick(timestamp)
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy/script_strategy_base.py", line 75, in tick
        self.on_tick()
      File "/home/rapcomia/github/hummingbot/7316/scripts/v2_with_controllers.py", line 84, in on_tick
        self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
      File "/home/rapcomia/github/hummingbot/7316/scripts/v2_with_controllers.py", line 84, in <dictcomp>
        self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 194, in generate_performance_report
        executor_info = executor.executor_info
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
        net_pnl_pct=self.net_pnl_pct,
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
        return self.get_net_pnl_pct()
      File "/home/rapcomia/github/hummingbot/7316/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 110, in get_net_pnl_pct
        return self.net_pnl_quote / self.buy_order.order.executed_amount_base
    AttributeError: 'NoneType' object has no attribute 'executed_amount_base'
    ```
      - Stop command initiated however still returning same error ❌
      - Status does not show anything ❌

Steps to reproduce:
1. Import the attached files to controller and script config of this PR
2. Start the v2 controller and select the conf 
3. Observed behavior

[12162024.zip](https://github.com/user-attachments/files/18150935/12162024.zip)

2024-12-17 03:34 UTC, rapcmia commented
PR update `69ad044539106387da2e05c636c917a87ab8ed18`

Review bot running using `grid_strike_grid_component.py` controller
- No error related to previous typeError, seems fixed when using binance ✅ 
- Orders placed, cancelled and filled ✅ 
- Executors opened and closed
   - Observed partial filled events on closing orders 
   - Observed accumulated order amount used when closing orders 
- Im all okay with this controller ✅ 

---

Review bot using `arbitrage_controller.py` controller
> - Getting Error updating executors info ❌
> - Getting Unexpected  error running clock tick ❌
> - Stop command initiated however still returning same error ❌
> - Status does not show anything ❌

Reported issues above has been fixed ✅ 

Run arbitrage controller config with Okx / Dexalot 
![image](https://github.com/user-attachments/assets/ac49eb58-3a54-431d-852c-e9ab9fe39bc4)
- I think we have enough balance to place sell orders for AVAX pairs {USDT/USDT} however it still returning an insufficient balance
- I tried to change the total amount in quote equivalent to the base asset but still same error 
- This has been stuck on same insufficient balance since started

Steps to reproduce:
- Import the attached files to controller and script config of this PR
- Start the v2 controller and select the conf
- Observed behavior

[12172024-arb-okxdexalot.zip](https://github.com/user-attachments/files/18159552/12172024-arb-okxdexalot.zip)

---

Run arbitrage controller config with Okx / Pangolin (w/ gateway)
![image](https://github.com/user-attachments/assets/22241f43-9fb1-48b4-8399-351fb31fe721)
![image](https://github.com/user-attachments/assets/8a99e42f-1ca5-4f42-ad29-d2f5b3509c75)
```
2024-12-17 10:22:34,009 - 79199 - hummingbot.strategy.script_strategy_base - ERROR - Error adding controller: 'avalanche'
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 222, in add_controller
    controller = config.get_controller_class()(config, self.market_data_provider, self.actions_queue)
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/controllers/generic/arbitrage_controller.py", line 50, in __init__
    gas_token = self.get_gas_token(connector_pair.connector_name)
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/controllers/generic/arbitrage_controller.py", line 61, in get_gas_token
    return self.gas_token_by_network[chain]
KeyError: 'avalanche'
2024-12-17 10:23:35,029 - 79199 - hummingbot.strategy.script_strategy_base - ERROR - Error adding controller: 'avalanche'
```
- Does not look for arbitrage opportunity and stuck on `Error adding controller avalanche`

Steps to reproduce:
- Import the attached files to controller and script config of this PR
- Setup gateway and add pangolin APi keys 
- Start the v2 controller and select the conf
- Observed behavior

[12172024_okxpangolin.zip](https://github.com/user-attachments/files/18159575/12172024_okxpangolin.zip)

---

Handover task to @nikspz  for Uniswap-Arbitrum test

2024-12-17 18:54 UTC, nikspz commented
> PR update `69ad044539106387da2e05c636c917a87ab8ed18`
> Run arbitrage controller config with Okx / Dexalot ![image](https://private-user-images.githubusercontent.com/73840223/396335409-ac49eb58-3a54-431d-852c-e9ab9fe39bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzQ4ODcsIm5iZiI6MTczNDQzNDU4NywicGF0aCI6Ii83Mzg0MDIyMy8zOTYzMzU0MDktYWM0OWViNTgtM2E1NC00MzFkLTg1MmMtZTlhYjlmZTM5YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDExMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MzBmMjBlMWFjZTQ0N2M5ZDBhZWYyM2ZiODk1NzE5NTVlYzE1MTY2OWU3ODMyMDZiNWZiZjZhOGZjNjc3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hlYaRN42vRCwvIsRjWyIuTrHagc8QA5EUcER7VCwB7k)
> 
> * I think we have enough balance to place sell orders for AVAX pairs {USDT/USDT} however it still returning an insufficient balance
> * I tried to change the total amount in quote equivalent to the base asset but still same error
> * This has been stuck on same insufficient balance since started

You should use order_amount in base (instead of 15), not total balance
![image](https://github.com/user-attachments/assets/bf4ec052-580c-4c7c-8d3f-e5a82ca0b7f3)

2024-12-18 07:24 UTC, rapcmia commented
PR update `013123d944cb1ddbaf0500708c8f8e33d5a0082e`
- Review again `generic.arbitrage_controller.py`
- Found that order amount must be set to equivalent to base token ✅ 
- What happens if any of the market (base/quoute) does not enough balance?
   ![image](https://github.com/user-attachments/assets/f6592c89-c39a-4746-a863-253b964dc73d)
   - Returns warning to user on logs ✅
- What happens if i set `max_executors_imbalance` to 2?
   - It will try to consider another buy or sell executor before it stop create ✅
      ![image](https://github.com/user-attachments/assets/d382a822-a4a3-4b5b-a266-df6525db0e9d)
- What happens if you stop the strategy while arbitrage executor is open? 
    ![image](https://github.com/user-attachments/assets/f95f974d-868a-417c-9500-29cc0981138c)
      - A market order will be placed on the other arbitrage leg and closes the executor ✅ 
      
---

### Run test with OKX / Pangolin ❗ 

> 2024-12-17 10:22:34,009 - 79199 - hummingbot.strategy.script_strategy_base - ERROR - Error adding controller: 'avalanche'
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/strategy/strategy_v2_base.py", line 222, in add_controller
    controller = config.get_controller_class()(config, self.market_data_provider, self.actions_queue)
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/controllers/generic/arbitrage_controller.py", line 50, in __init__
    gas_token = self.get_gas_token(connector_pair.connector_name)
  File "/Users/rapcomia/github/hummingbot/hummingbot/7316/controllers/generic/arbitrage_controller.py", line 61, in get_gas_token
    return self.gas_token_by_network[chain]
KeyError: 'avalanche'
2024-12-17 10:23:35,029 - 79199 - hummingbot.strategy.script_strategy_base - ERROR - Error adding controller: 'avalanche'

User must manually add the chain and token on `gas_token_by_network` ✅ 
![image](https://github.com/user-attachments/assets/ee65c8ff-4eac-44a8-b70a-17e7f723a0fe)
- After adding these chains and token, error fixed ✅ 
- Market order on CEX ✅
- However for `Pangolin` got an error when placing orders `ValueError...Swap price 46.55970313 exceeds limitPrice 46.55970300000000000000` ❌ 
  ```
  2024-12-18 13:15:09,858 - 67841 - GatewayEVMAMM - ERROR - Error submitting BUY swap order to pangolin on avalanche for 0.320000 WAVAX-USDC 46.559703000000000.
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 558, in _create_order
      order_result: Dict[str, Any] = await self._get_gateway_instance().amm_trade(
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/core/gateway/gateway_http_client.py", line 518, in amm_trade
      return await self.api_request("post", "amm/trade", request_payload)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/core/gateway/gateway_http_client.py", line 222, in api_request
      raise e
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/core/gateway/gateway_http_client.py", line 210, in api_request
      raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
  ValueError: Error on POST https://localhost:15888/amm/trade Error: {'message': 'Swap price 46.55970313 exceeds limitPrice 46.55970300000000000000', 'httpErrorCode': 500, 'errorCode': 1008, 'stack': 'Error: Swap price 46.55970313 exceeds limitPrice 46.55970300000000000000\n    at /Users/rapcomia/github/hummingbot/gateway/gw-development/dist/src/connectors/uniswap/uniswap.controllers.js:132:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rapcomia/github/hummingbot/gateway/gw-development/dist/src/connectors/uniswap/uniswap.controllers.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
  2024-12-18 13:15:09,860 - 67841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734498909.0, "order_id": "buy-WAVAX-USDC-1734498908151084", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "pangolin_avalanche_avalanche"}
  2024-12-18 13:15:09,861 - 67841 - hummingbot.connector.client_order_tracker - INFO - Order buy-WAVAX-USDC-1734498908151084 has failed. Order Update: OrderUpdate(trading_pair='WAVAX-USDC', update_timestamp=1734498909.0, new_state=<OrderState.FAILED: 6>, client_order_id='buy-WAVAX-USDC-1734498908151084', exchange_order_id=None, misc_updates=None)
  2024-12-18 13:15:11,576 - 67841 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/trade failed. See logs for more details.
  ```
   - Ended stuck with `GatewayEVAMM-ERROR` ❌ 
      ```
      2024-12-18 13:15:39,004 - 67841 - GatewayEVMAMM - ERROR - 
      Traceback (most recent call last):
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/connector/gateway/gateway_in_flight_order.py", line 102, in get_exchange_order_id
          await self.exchange_order_id_update_event.wait()
        File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/locks.py", line 214, in wait
          await fut
      asyncio.exceptions.CancelledError
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 928, in _status_polling_loop
          await safe_gather(
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
          return await asyncio.gather(*args, **kwargs)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 789, in update_order_status
          tx_hash_list: List[str] = await safe_gather(
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
          return await asyncio.gather(*args, **kwargs)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316/hummingbot/connector/gateway/gateway_in_flight_order.py", line 101, in get_exchange_order_id
          async with timeout(GET_GATEWAY_EX_ORDER_ID_TIMEOUT):
        File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 179, in __aexit__
          self._do_exit(exc_type)
        File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 265, in _do_exit
          raise asyncio.TimeoutError
      asyncio.exceptions.TimeoutError
      ``` 

Steps to reproduce:
- Import controller config from attached file
- Change `min_profitability` to a value enough to trigger arbitrage 
- Observe when placing orders on DEX (gateway) side 

[12182024_okxpangolin.zip](https://github.com/user-attachments/files/18176470/12182024_okxpangolin.zip)

---

### Run tests again on OKX / Dexalot ✅ 
- Setup both API keys okay
- Added `dexalot: AVAX` to `gas_token_by_network`
- Start the strategy:
  - Observed that the profitability has stopped and only the other leg is changing ✅ 
     ![image](https://github.com/user-attachments/assets/c4ae0450-7abd-44d1-b01c-5d17745bef1e)
  - Got opportunity to sell on okx and buy on dexalot ✅ 
     ![image](https://github.com/user-attachments/assets/f0b50fd3-73e2-47ed-87dd-3e3844993bc4)
  - Now showing a new tab for arbitrage opportunity ✅ 
     ![image](https://github.com/user-attachments/assets/b84557d1-a6b4-4bed-8e1c-603b7da36453)

---

### Run tests on OKX / Uniswap_Polygon_Mainnet ❗ 
- Added POL with same value as MATIC and updated USDC on `polygon_token_mainnet.json` ✅ 
  ![image](https://github.com/user-attachments/assets/4ef15b7a-dccc-4acd-abc4-4ade8af97de5)
- Updated Arbitrage controller ✅ 
  ![image](https://github.com/user-attachments/assets/03c6a4bf-0cc9-4e3b-8778-d890a8f03f93)
- Approved W [...]

2024-12-18 19:41 UTC, nikspz commented
013123d

grid_strike_grid_component Tests: 
1. Cloned and installed PR7316
2. create create --controller-config generic.grid_strike_grid_component, set up start_price: 25, end_price: 27.5, limit_price: 23.6
3. create --script-config v2_with_controllers using this controller
4. start the script and run till `time_limit: 21600` of triple_barrier_config triggered

Actual:
just closed the position with MARKET SELL order 0x266b5ca72bfc6b3fed1d02b38e996517 for 9.05 HYPE-USDC at 23.126000000000001.
`midprice at this timeframe is ~24.2` 

after it was closed with MARKET order bot stuck on Unexpected error running clock tick.
since after order filled total USDC is lower than 240 (total_amount_quote: 240)


[logs_hpl-gs-gc6low.zip](https://github.com/user-attachments/files/18187971/logs_hpl-gs-gc6low.zip)
[hpl-gs-gc6low.zip](https://github.com/user-attachments/files/18188065/hpl-gs-gc6low.zip)

```
2024-12-18 16:51:01,374 - 3375243 - hummingbot.connector.client_order_tracker - INFO - The SELL order 0x266b5ca72bfc6b3fed1d02b38e996517 amounting to 8.82/9.05 HYPE has been filled at 24.336 USDC.
2024-12-18 16:51:01,428 - 3375243 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734540661.0, "order_id": "0x266b5ca72bfc6b3fed1d02b38e996517", "trading_pair": "HYPE-USDC", "trade_type": "TradeType.SELL", "order_type": "OrderType.MARKET", "price": "24.336", "amount": "3.11", "trade_fee": {"percent": "0", "percent_token": "USDC", "flat_fees": [{"token": "USDC", "amount": "0.026489"}]}, "exchange_trade_id": "110337349861248", "exchange_order_id": "56311448018", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "hyperliquid"}
2024-12-18 16:51:02,987 - 3375243 - hummingbot.connector.exchange.hyperliquid.hyperliquid_exchange.HyperliquidExchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/in_flight_order.py", line 296, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/connector/exchange/hyperliquid/hyperliquid_exchange.py", line 484, in _user_stream_event_listener
    await self._process_trade_message(trade_msg)
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/connector/exchange/hyperliquid/hyperliquid_exchange.py", line 504, in _process_trade_message
    await v.get_exchange_order_id()
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/in_flight_order.py", line 295, in get_exchange_order_id
    async with timeout(GET_EX_ORDER_ID_TIMEOUT):
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 179, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 265, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2024-12-18 16:51:04,548 - 3375243 - hummingbot.connector.client_order_tracker - WARNING - The order fill updates did not arrive on time for 0x266b5ca72bfc6b3fed1d02b38e996517. The complete update will be processed with incomplete information.
2024-12-18 16:51:04,563 - 3375243 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734540664.0, "order_id": "0x266b5ca72bfc6b3fed1d02b38e996517", "base_asset": "HYPE", "quote_asset": "USDC", "base_asset_amount": "8.82", "quote_asset_amount": "214.61008", "order_type": "OrderType.MARKET", "exchange_order_id": "56311448018", "event_name": "SellOrderCompletedEvent", "event_source": "hyperliquid"}
2024-12-18 16:51:04,564 - 3375243 - hummingbot.connector.client_order_tracker - INFO - SELL order 0x266b5ca72bfc6b3fed1d02b38e996517 completely filled.
2024-12-18 16:51:05,692 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:06,144 - 3375243 - hummingbot.connector.client_order_tracker - WARNING - The order fill updates did not arrive on time for 0x266b5ca72bfc6b3fed1d02b38e996517. The complete update will be processed with incomplete information.
2024-12-18 16:51:11,746 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:17,767 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:23,978 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:29,992 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:36,016 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:42,097 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:48,347 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - INFO - Waiting for close order to be filled
2024-12-18 16:51:54,634 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:51:55,634 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:51:56,638 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:51:57,644 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:51:58,648 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:51:59,651 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:00,668 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:01,658 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:02,668 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:03,674 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:04,674 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:05,676 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:06,681 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:07,685 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:08,692 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:09,691 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:10,694 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - Not enough budget to open position.
2024-12-18 16:52:11,692 - 3375243 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - [...]

2024-12-19 07:12 UTC, rapcmia commented
PR update `ca6c1555d098ba22cb1939461ddecbdc5beb1c35`

Run arbitrage controller
- Run okx / dexalot ✅
- Run okx / pangolin ✅
- Run okx / uniswap polygon
    - updated tokenlist ✅
    - After successful arbitrage, getting error on logs every tick
      ```
      2024-12-19 15:00:10,001 - 90354 - hummingbot.strategy.script_strategy_base - ERROR - Error updating executors info: Could not find the exchange rate for MATIC-USDC using the rate source binance rate oracle (please verify it has been correctly configured)
      Traceback (most recent call last):
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy/strategy_v2_base.py", line 266, in update_executors_info
          self.executors_info = self.executor_orchestrator.get_executors_report()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in get_executors_report
          report[controller_id] = [executor.executor_info for executor in executors_list if executor]
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in <listcomp>
          report[controller_id] = [executor.executor_info for executor in executors_list if executor]
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
          net_pnl_pct=self.net_pnl_pct,
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
          return self.get_net_pnl_pct()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 121, in get_net_pnl_pct
          return self.net_pnl_quote / self.buy_order.order.executed_amount_base
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 201, in net_pnl_quote
          return self.get_net_pnl_quote()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 114, in get_net_pnl_quote
          return sell_quote_amount - buy_quote_amount - self.cum_fees_quote
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 215, in cum_fees_quote
          return self.get_cum_fees_quote()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 128, in get_cum_fees_quote
          return self.buy_order.cum_fees_quote + self.sell_order.cum_fees_quote
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/models/executors.py", line 100, in cum_fees_quote
          return self.order.cumulative_fee_paid(token=self.order.quote_asset)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
          total_fee_in_token += trade_update.fee.fee_amount_in_token(
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
          conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
          raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
      ValueError: Could not find the exchange rate for MATIC-USDC using the rate source binance rate oracle (please verify it has been correctly configured)
      2024-12-19 15:00:10,007 - 90354 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
      Traceback (most recent call last):
        File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
          child_iterator.c_tick(self._current_tick)
        File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
          self.tick(timestamp)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy/script_strategy_base.py", line 75, in tick
          self.on_tick()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/scripts/v2_with_controllers.py", line 84, in on_tick
          self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/scripts/v2_with_controllers.py", line 84, in <dictcomp>
          self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 194, in generate_performance_report
          executor_info = executor.executor_info
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
          net_pnl_pct=self.net_pnl_pct,
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
          return self.get_net_pnl_pct()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 121, in get_net_pnl_pct
          return self.net_pnl_quote / self.buy_order.order.executed_amount_base
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 201, in net_pnl_quote
          return self.get_net_pnl_quote()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 114, in get_net_pnl_quote
          return sell_quote_amount - buy_quote_amount - self.cum_fees_quote
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 215, in cum_fees_quote
          return self.get_cum_fees_quote()
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 128, in get_cum_fees_quote
          return self.buy_order.cum_fees_quote + self.sell_order.cum_fees_quote
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/models/executors.py", line 100, in cum_fees_quote
          return self.order.cumulative_fee_paid(token=self.order.quote_asset)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
          total_fee_in_token += trade_update.fee.fee_amount_in_token(
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
          conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
        File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
          raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
      ValueError: Could not find the exchange rate for MATIC-USDC using the rate source binance rate oracle (please verify it has been correctly configured)
      2024-12-19 15:00:10,657 - 90354 - hummingbot.client.performance - WARNING - Could not find exchange rate for MATIC-USDC using binance rate [...]

2024-12-19 14:20 UTC, fengtality commented
Looks like the errors are from using MATIC instead of POL

Michael Feng
***@***.***
+1 908 938 8733


On Wed, Dec 18, 2024 at 11:12 PM Ralph Arvid B. Comia <
***@***.***> wrote:

> PR update ca6c1555d098ba22cb1939461ddecbdc5beb1c35
>
> Run arbitrage controller
>
>    - Run okx / dexalot ✅
>    - Run okx / pangolin ✅
>    - Run okx / uniswap polygon
>       - updated tokenlist ✅
>       - After successful arbitrage, getting error on logs every tick
>
>       2024-12-19 15:00:10,001 - 90354 - hummingbot.strategy.script_strategy_base - ERROR - Error updating executors info: Could not find the exchange rate for MATIC-USDC using the rate source binance rate oracle (please verify it has been correctly configured)
>       Traceback (most recent call last):
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy/strategy_v2_base.py", line 266, in update_executors_info
>           self.executors_info = self.executor_orchestrator.get_executors_report()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in get_executors_report
>           report[controller_id] = [executor.executor_info for executor in executors_list if executor]
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 184, in <listcomp>
>           report[controller_id] = [executor.executor_info for executor in executors_list if executor]
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
>           net_pnl_pct=self.net_pnl_pct,
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
>           return self.get_net_pnl_pct()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 121, in get_net_pnl_pct
>           return self.net_pnl_quote / self.buy_order.order.executed_amount_base
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 201, in net_pnl_quote
>           return self.get_net_pnl_quote()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 114, in get_net_pnl_quote
>           return sell_quote_amount - buy_quote_amount - self.cum_fees_quote
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 215, in cum_fees_quote
>           return self.get_cum_fees_quote()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 128, in get_cum_fees_quote
>           return self.buy_order.cum_fees_quote + self.sell_order.cum_fees_quote
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/models/executors.py", line 100, in cum_fees_quote
>           return self.order.cumulative_fee_paid(token=self.order.quote_asset)
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
>           total_fee_in_token += trade_update.fee.fee_amount_in_token(
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
>           conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
>           raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
>       ValueError: Could not find the exchange rate for MATIC-USDC using the rate source binance rate oracle (please verify it has been correctly configured)
>       2024-12-19 15:00:10,007 - 90354 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
>       Traceback (most recent call last):
>         File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
>           child_iterator.c_tick(self._current_tick)
>         File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
>           self.tick(timestamp)
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy/script_strategy_base.py", line 75, in tick
>           self.on_tick()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/scripts/v2_with_controllers.py", line 84, in on_tick
>           self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/scripts/v2_with_controllers.py", line 84, in <dictcomp>
>           self.performance_reports = {controller_id: self.executor_orchestrator.generate_performance_report(controller_id=controller_id).dict() for controller_id in self.controllers.keys()}
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 194, in generate_performance_report
>           executor_info = executor.executor_info
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 118, in executor_info
>           net_pnl_pct=self.net_pnl_pct,
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 208, in net_pnl_pct
>           return self.get_net_pnl_pct()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 121, in get_net_pnl_pct
>           return self.net_pnl_quote / self.buy_order.order.executed_amount_base
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 201, in net_pnl_quote
>           return self.get_net_pnl_quote()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 114, in get_net_pnl_quote
>           return sell_quote_amount - buy_quote_amount - self.cum_fees_quote
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/executor_base.py", line 215, in cum_fees_quote
>           return self.get_cum_fees_quote()
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/executors/arbitrage_executor/arbitrage_executor.py", line 128, in get_cum_fees_quote
>           return self.buy_order.cum_fees_quote + self.sell_order.cum_fees_quote
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/strategy_v2/models/executors.py", line 100, in cum_fees_quote
>           return self.order.cumulative_fee_paid(token=self.order.quote_asset)
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
>           total_fee_in_token += trade_update.fee.fee_amount_in_token(
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
>           conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
>         File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
>           raise ValueError(f"Could not find the exchange rate for {tradin [...]

2024-12-19 17:25 UTC, nikspz commented
9be6d6b

arbitrage_controller Tests:
- Cloned and installed PR7316
- create create --controller-config arbitrage_controller, using mexc and uniswap_ethereum_base ✅
- create --script-config v2_with_controllers using this controller
- started the script successfully, review both buy and sell filled successfully ✅
- review ERROR - Error calculating fee in quote: 'GatewayEVMAMM' object has no attribute 'order_books', will be stored in the DB as 0. after first sell on uniswap eth base completed
- set max_executors_imbalance: 2 to review few trades one after one 
- reviewed buy/sell then another buy/sell after delay_between_executors ✅

[logs_base8.log](https://github.com/user-attachments/files/18201260/logs_base8.log)
[!19 decbase.zip](https://github.com/user-attachments/files/18201272/19.decbase.zip)

2024-12-19 18:06 UTC, fengtality commented
update your Hummingbot branch to the latest solana-gateway-changes PR. The
order books error shouldn't appear.

On Thu, Dec 19, 2024, 9:26 AM nikspz ***@***.***> wrote:

> 9be6d6b
> <https://github.com/hummingbot/hummingbot/commit/9be6d6bc0a52b6bcf609a01ed3e6af964d0d841f>
>
> arbitrage_controller Tests:
>
>    - Cloned and installed PR7316
>    - create create --controller-config arbitrage_controller, using mexc
>    and uniswap_ethereum_base ✅
>    - create --script-config v2_with_controllers using this controller
>    - started the script successfully, review both buy and sell filled
>    successfully ✅
>    - review ERROR - Error calculating fee in quote: 'GatewayEVMAMM'
>    object has no attribute 'order_books', will be stored in the DB as 0. after
>    first sell on uniswap eth base completed
>    - set max_executors_imbalance: 2 to review few trades one after one
>    - reviewed buy/sell then another buy/sell after
>    delay_between_executors ✅
>
> logs_base8.log
> <https://github.com/user-attachments/files/18201260/logs_base8.log>
> !19 decbase.zip
> <https://github.com/user-attachments/files/18201272/19.decbase.zip>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hummingbot/hummingbot/pull/7316#issuecomment-2555261631>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANWHVUS7KFZQX66MOR7VRL2GL6TDAVCNFSM6AAAAABSTSA4U6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJVGI3DCNRTGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-19 19:51 UTC, nikspz commented
> update your Hummingbot branch to the latest solana-gateway-changes PR. The order books error shouldn't appear.

ff668661c61090ee5f36d71ebad4fc6ca7085865 + latest gateway development (6be2b2d35fcd7b06bd7011eb47ad28cec97614aa)

arbitrage_controller Tests:
- Cloned and installed PR7316
- create create --controller-config arbitrage_controller, using mexc and uniswap_ethereum_base ✅
- create --script-config v2_with_controllers using this controller
- started the script successfully, review both buy and sell filled successfully ✅
- No ERROR - Error calculating fee in quote: 'GatewayEVMAMM' object has no attribute 'order_books' showed after sell order filled ✅

![image](https://github.com/user-attachments/assets/5ee4867b-3513-47ba-b536-b7bd09f422ea)

2024-12-19 20:54 UTC, nikspz commented
e704cbe + latest gateway development (6be2b2d35fcd7b06bd7011eb47ad28cec97614aa)

arbitrage_controller Tests:
- Cloned and installed PR7316
- create create --controller-config arbitrage_controller, using mexc and uniswap_ethereum_base ✅
- create --script-config v2_with_controllers using this controller
- started the script successfully, review both buy and sell filled successfully ✅
- No ERROR - Error calculating fee in quote: 'GatewayEVMAMM' object has no attribute 'order_books' showed after sell order filled ✅

![image](https://github.com/user-attachments/assets/6fe3f4cb-dbbf-446a-8c3f-2829095bf87b)

2024-12-23 04:37 UTC, rapcmia commented
PR update on commit `89483b8bf591178bbf0f17b1008773c3f709e960`
- Observed that the order amount seems to be not used anymore and follows the set `total_amount_in_quote`
    ![image](https://github.com/user-attachments/assets/d2ce6c26-fc31-4ab1-a2d7-b72869e2e2a7)
  - The buy and sell order are placed using 0.802AVAX (29.409340000000004 USD) when it should be 0.40AVAX(15USD)
    ![image](https://github.com/user-attachments/assets/2b58f39e-923e-478e-8a11-2d4c47e2d946)

---
### Run tests on arbitrage_controller
- Buy order seem to work okay
- Error happened when sell order was filled on OKX as market order ❌ 
- Run same controller and script twice with different configs got same error ❌ 
- The error only happens strategy place sell market order
  - Getting Unexpected error while processing event 107.
  ```
  2024-12-23 00:00:11,896 - 48107 - hummingbot.connector.client_order_tracker - INFO - The SELL order 0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed amounting to 0.81/0.810 AVAX has been filled at 36.955 USDC.
  2024-12-23 00:00:11,897 - 48107 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734883211.0, "order_id": "0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed", "trading_pair": "AVAX-USDC", "trade_type": "TradeType.SELL", "order_type": "OrderType.MARKET", "price": "36.955", "amount": "0.81", "trade_fee": {"percent": "0", "percent_token": "USDC", "flat_fees": [{"token": "USDC", "amount": "0.035"}]}, "exchange_trade_id": "1893403308", "exchange_order_id": "0x0000000000000000000000000000000000000000000000000000000070db0aab", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "dexalot"}
  2024-12-23 00:00:11,906 - 48107 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - ERROR - Unexpected error while processing event 107.
  Traceback (most recent call last):
    File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
      typed_listener.c_call(arg)
    File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
      self(arg)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/event/event_forwarder.py", line 24, in __call__
      self._to_function(self.current_event_tag, self.current_event_caller, arg)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/markets_recorder.py", line 392, in _did_fill_order
      self.save_market_states(self._config_file_path, market, session=session)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/markets_recorder.py", line 275, in save_market_states
      saved_state=market.tracking_states)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/exchange_py_base.py", line 195, in tracking_states
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/exchange_py_base.py", line 195, in <dictcomp>
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 268, in to_json
      "cumulative_fee_paid_base": float(self.cumulative_fee_paid(self.base_asset)),
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
      total_fee_in_token += trade_update.fee.fee_amount_in_token(
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
      fee_amount += (str(flat_fee.amount)) * conversion_rate
  TypeError: can't multiply sequence by non-int of type 'decimal.Decimal'
  2024-12-23 00:00:11,913 - 48107 - hummingbot.connector.client_order_tracker - INFO - Created MARKET SELL order 0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed for 0.810 AVAX-USDC at 0.
  2024-12-23 00:00:11,913 - 48107 - hummingbot.strategy_v2.executors.arbitrage_executor.arbitrage_executor - INFO - Sell Order Created
  2024-12-23 00:00:11,913 - 48107 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734883211.0, "type": "OrderType.MARKET", "trading_pair": "AVAX-USDC", "amount": "0.810", "price": "0", "order_id": "0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed", "creation_timestamp": 1734883204.0, "exchange_order_id": "0x0000000000000000000000000000000000000000000000000000000070db0aab", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "dexalot"}
  ```
  - Getting Unexpected error while processing event 201.
  ```
  2024-12-23 00:00:11,917 - 48107 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - ERROR - Unexpected error while processing event 201.
  Traceback (most recent call last):
    File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
      typed_listener.c_call(arg)
    File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
      self(arg)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/event/event_forwarder.py", line 24, in __call__
      self._to_function(self.current_event_tag, self.current_event_caller, arg)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/markets_recorder.py", line 332, in _did_create_order
      self.save_market_states(self._config_file_path, market, session=session)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/markets_recorder.py", line 275, in save_market_states
      saved_state=market.tracking_states)
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/exchange_py_base.py", line 195, in tracking_states
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/connector/exchange_py_base.py", line 195, in <dictcomp>
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 268, in to_json
      "cumulative_fee_paid_base": float(self.cumulative_fee_paid(self.base_asset)),
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
      total_fee_in_token += trade_update.fee.fee_amount_in_token(
    File "/Users/rapcomia/github/hummingbot/hummingbot/7316a/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
      fee_amount += (str(flat_fee.amount)) * conversion_rate
  TypeError: can't multiply sequence by non-int of type 'decimal.Decimal'
  2024-12-23 00:00:11,918 - 48107 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734883211.0, "order_id": "0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed", "base_asset": "AVAX", "quote_asset": "USDC", "base_asset_amount": "0.81", "quote_asset_amount": "29.93355", "order_type": "OrderType.MARKET", "exchange_order_id": "0x0000000000000000000000000000000000000000000000000000000070db0aab", "event_name": "SellOrderCompletedEvent", "event_source": "dexalot"}
  2024-12-23 00:00:11,919 - 48107 - hummingbot.connector.client_order_tracker - INFO - SELL order 0xf57688f18fd1fbaedf45a9022a1b62dd5069b90e94d1bd8cd3560fb9c5312aed completely filled.
  ```
  - Observe delay to non recorded fills
      - See recording here https://drive.google.com/file/d/15TySJ6bGA7CUOgJt9L2nzJLp1J9dPyRQ/view?usp=drive_link
- These behaviors are observed from 
  - Arb OKX / Dexalot ❌ 
  - Arb OKX / Pangolin ❌ 
 [...]

2024-12-23 05:51 UTC, rapcmia commented
Update when running test with `grid_strike_grid_component.py`
- Getting same `Unexpected error while processing event 107 and 102` ❌ 
  ![image](https://github.com/user-attachments/assets/b4f55fec-74b6-4597-827e-29f93e002410)
  ```
  2024-12-23 05:10:01,030 - 229861 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
  2024-12-23 05:10:02,022 - 229861 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT629e902388ee2ee9e for 21 to OPEN a PNUT-USDT position at 0.6857100.
  2024-12-23 05:10:02,105 - 229861 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734930602.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "21", "price": "0.6857100", "order_id": "x-nbQe1H39BPTUT629e902388ee2ee9e", "creation_timestamp": 1734930601.0, "exchange_order_id": "2308540080", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
  2024-12-23 05:10:02,111 - 229861 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT629e9023891bdee9e for 21 to OPEN a PNUT-USDT position at 0.6986000.
  2024-12-23 05:10:02,185 - 229861 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734930602.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "21", "price": "0.6986000", "order_id": "x-nbQe1H39BPTUT629e9023891bdee9e", "creation_timestamp": 1734930601.0, "exchange_order_id": "2308540082", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
  2024-12-23 05:10:02,186 - 229861 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-nbQe1H39BPTUT629e90238932bee9e for 21 to OPEN a PNUT-USDT position at 0.6500000.
  2024-12-23 05:10:02,218 - 229861 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734930602.0, "type": "OrderType.LIMIT", "trading_pair": "PNUT-USDT", "amount": "21", "price": "0.6500000", "order_id": "x-nbQe1H39BPTUT629e90238932bee9e", "creation_timestamp": 1734930601.0, "exchange_order_id": "2308540083", "leverage": 30, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
  2024-12-23 05:10:04,067 - 229861 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-nbQe1H39BPTUT629e9023891bdee9e amounting to 21/21 PNUT has been filled at 0.6986000 USDT.
  2024-12-23 05:10:04,121 - 229861 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - ERROR - Unexpected error while processing event 107.
  Traceback (most recent call last):
    File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
      typed_listener.c_call(arg)
    File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
      self(arg)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/event/event_forwarder.py", line 24, in __call__
      self._to_function(self.current_event_tag, self.current_event_caller, arg)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 392, in _did_fill_order
      self.save_market_states(self._config_file_path, market, session=session)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 269, in save_market_states
      market_states.saved_state = market.tracking_states
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 195, in tracking_states
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 195, in <dictcomp>
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/in_flight_order.py", line 268, in to_json
      "cumulative_fee_paid_base": float(self.cumulative_fee_paid(self.base_asset)),
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
      total_fee_in_token += trade_update.fee.fee_amount_in_token(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
      fee_amount += (str(flat_fee.amount)) * conversion_rate
  TypeError: can't multiply sequence by non-int of type 'decimal.Decimal'
  2024-12-23 05:10:04,132 - 229861 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734930604.0, "order_id": "x-nbQe1H39BPTUT629e9023891bdee9e", "trading_pair": "PNUT-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0.6986000", "amount": "21", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.00293412"}]}, "exchange_trade_id": "184941344", "exchange_order_id": "2308540082", "leverage": 30, "position": "OPEN", "event_name": "OrderFilledEvent", "event_source": "binance_perpetual"}
  2024-12-23 05:10:04,256 - 229861 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-12-23 05:10:04,292 - 229861 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - ERROR - Unexpected error while processing event 102.
  Traceback (most recent call last):
    File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
      typed_listener.c_call(arg)
    File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
      self(arg)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/event/event_forwarder.py", line 24, in __call__
      self._to_function(self.current_event_tag, self.current_event_caller, arg)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 495, in _did_complete_order
      self._update_order_status(event_tag, market, evt)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 477, in _update_order_status
      self.save_market_states(self._config_file_path, market, session=session)
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/markets_recorder.py", line 269, in save_market_states
      market_states.saved_state = market.tracking_states
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 195, in tracking_states
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/connector/exchange_py_base.py", line 195, in <dictcomp>
      return {key: value.to_json() for key, value in self._order_tracker.all_updatable_orders.items()}
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/in_flight_order.py", line 268, in to_json
      "cumulative_fee_paid_base": float(self.cumulative_fee_paid(self.base_asset)),
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
      total_fee_in_token += trade_update.fee.fee_amount_in_token(
    File "/home/rapcomia/github/hummingbot/7316/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
      fee_amount += (str(flat_fee.amount)) * conversion_rate
  TypeError: can't multiply sequence by non-int of type 'decimal.Decimal'
  2024-12-23 05:10:04,293 - 229861 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734930604.0, "order_id": "x-nbQe1H39BPTUT629e9023891bdee9e", "base_asset": "PNUT", "quote_asset": "USDT", "base_asset_amount": "21", "quote_asset_amount": "14. [...]

2024-12-23 07:42 UTC, nikspz commented
89483b8

Steps:
1. Cloned PR7316
2. used grid_strike_grid_component generic controller, HYPE-USDC
3. started v2_with_controllers

Actual:
After few trades review 
ERROR - Unexpected error while processing event 107, 103, 106
then bot stuck on  ERROR - can't multiply sequence by non-int of type 'decimal.Decimal' (File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
    fee_amount += (str(flat_fee.amount)) * conversion_rate)


[!23 dec.zip](https://github.com/user-attachments/files/18226579/23.dec.zip)

[hpl-gs-gc10.zip](https://github.com/user-attachments/files/18226466/hpl-gs-gc10.zip)
[logs_hpl-gs-gc10.log](https://github.com/user-attachments/files/18226473/logs_hpl-gs-gc10.log)

```
2024-12-23 07:22:07,699 - 3481965 - hummingbot.strategy_v2.executors.grid_executor.grid_executor - ERROR - can't multiply sequence by non-int of type 'decimal.Decimal'
Traceback (most recent call last):
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
    await self.control_task()
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/executors/grid_executor/grid_executor.py", line 192, in control_task
    self.update_grid_levels()
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/strategy_v2/executors/grid_executor/grid_executor.py", line 238, in update_grid_levels
    close_order = level.active_close_order.order.to_json()
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/in_flight_order.py", line 268, in to_json
    "cumulative_fee_paid_base": float(self.cumulative_fee_paid(self.base_asset)),
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/in_flight_order.py", line 308, in cumulative_fee_paid
    total_fee_in_token += trade_update.fee.fee_amount_in_token(
  File "/home/hummingbot/nikita/7316executorsimp/hummingbot/core/data_type/trade_fee.py", line 227, in fee_amount_in_token
    fee_amount += (str(flat_fee.amount)) * conversion_rate
TypeError: can't multiply sequence by non-int of type 'decimal.Decimal'
```


![image](https://github.com/user-attachments/assets/b90b0a8c-fcc6-480c-b2e4-ad6902e5b682)

![image](https://github.com/user-attachments/assets/fd03b7ee-2f60-461e-b171-383eadb89c35)

2024-12-24 05:44 UTC, rapcmia approved these changes
- Run tests on source ok
- Create controller config, ok but no user prompt
- Create bots and run:
  - generic.arbitrage_controller.py
	  - Run test on okx/dexalot, okx/pangolin and okx/uniswap_polygon
	  - When started, waits for a opportunity base on the set `min_profitability`
	  - When filled, waits for the other leg to be completed before creating a new set of arbitrage 
	  - When insufficient balance, displays 0 on status and only executes the leg that has inventory
	  - When set max_executors to more than 1, It will try to consider another buy or sell executor before it going to another set of arbitrage
	  - When a executor is opened and initiated stop command, places market order to close executor 
	  - Review closeTypes recorded are either completed(9), early_stop(5) and insufficient_balance(7)
	   - Note: 
	    - Need to run a long term bot for early_stop behavior since it normally happens when an executor is stopped
	    - Observed limitation of CLOB DEXes when used on Arbitrage (Will open separate ticket)
  - generic.grid_strike_grid_component.py
    - Run tests on binance_perp using PNUUSDT
    - Same as creating config above, does not prompt user inputs. 
    - Review config and modified base on test preference 
    - Run bots long term and observe behavior base on config ok
    - Set side in which direction the config should do (long or short grid)
	  - Observe start price, end_price and limit_price 
	  - Change order types base on test preference which works as expected 
	  - Orders are created per `max_order_per_batch` and can only place after set `order_frequency` and limits the number of open orders using `max_pen_orders`
	  - Opens executor, accumulate the order size then uses it when hits TP or TIME_LIMIT place market order to close executor.
	  - Review trade data on sqlite ok
  - Market data provider
		- Observe no failure on exchange rates when tested:
			- Cex / Clob Dex
			- Cex / AMM Dex
			  - Observe gateway errors not related to this PR, will continue running tests and open ticket

2024-12-24 07:29 UTC, nikspz commented
commit [9c9d879](https://github.com/hummingbot/hummingbot/pull/7316/commits/9c9d8796629420e04a3ecc5f0e019f2b7be0949c)

There's `total_amount_quote` variable name instead of `order_amount_in_quote`
 
 
 config:
 ```
 id: 4G8Ne6d9NQQkm7zVUM343f2iJVe7QSDgk7DHsAEhRcdr
controller_name: arbitrage_controller
controller_type: generic
total_amount_quote: 28
manual_kill_switch: null
candles_config: []
exchange_pair_1:
  connector_name: mexc
  trading_pair: BAI-USDT
exchange_pair_2:
  connector_name: uniswap_ethereum_base
  trading_pair: BAI-USDC
min_profitability: 0.01
delay_between_executors: 10
max_executors_imbalance: 1
rate_connector: mexc
quote_conversion_asset: USDC

 ```
 
![image](https://github.com/user-attachments/assets/18853370-5831-40ce-be27-920cc1496abe)

![image](https://github.com/user-attachments/assets/af508964-7559-403c-bd9d-5f66fda5a208)

2024-12-24 09:00 UTC, nikspz commented
commit 9c9d879

BAI-USDT mexc + BAI-USDC uniswap ethereum base

reduced "total_amount_quote" to 7 (quote_conversion_asset: USDC)

1. first start: ❌
![image](https://github.com/user-attachments/assets/7f31b965-7f2b-477f-b759-acec2d29a0aa)

2. restarted same strategy after ~1min
was able to `execute buy and sell successfully` ✅✅ with Unexpected error while processing event 102, 107 (Could not find the exchange rate for USDT-BAI using the rate source binance rate oracle)


changed quote_conversion_asset to USDT: ⬅

1. MARKET order to open (BUY) cancelled on mexc ❌ ❌

2. sell order filled on uniswap eth base ✅

![image](https://github.com/user-attachments/assets/32069e03-0ee0-4bc7-8696-607b6d81a501)
![image](https://github.com/user-attachments/assets/a3f7e150-161d-4c10-b76d-53b6c333527f)

2024-12-25 05:58 UTC, nikspz commented
> commit [9c9d879](https://github.com/hummingbot/hummingbot/pull/7316/commits/9c9d8796629420e04a3ecc5f0e019f2b7be0949c)
> 
> There's `total_amount_quote` variable name instead of `order_amount_in_quote` (below this amount used as order amount in quote)
> 
> 
> ![image](https://private-user-images.githubusercontent.com/83953535/398352045-18853370-5831-40ce-be27-920cc1496abe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDYzNzIsIm5iZiI6MTczNTEwNjA3MiwicGF0aCI6Ii84Mzk1MzUzNS8zOTgzNTIwNDUtMTg4NTMzNzAtNTgzMS00MGNlLWJlMjctOTIwY2MxNDk2YWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA1NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxY2FjZjcxYmJjZmY2ZWEzMWNkMmI4MzY2MTgxMjI2MDY1MWRhNGIyZWFiODU3MTk2Mjc5ZTNmNmY0NDgzZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-RGYlEozipjhInC9ZesURV_PDkFfvT4FbS2WHoBSwV0)
> 
> ![image](https://private-user-images.githubusercontent.com/83953535/398350687-af508964-7559-403c-bd9d-5f66fda5a208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDYzNzIsIm5iZiI6MTczNTEwNjA3MiwicGF0aCI6Ii84Mzk1MzUzNS8zOTgzNTA2ODctYWY1MDg5NjQtNzU1OS00MDNjLWJkOWQtNWY2NmZkYTVhMjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA1NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTQ0MDE1OGI2NWFiYTZhNDJjYmQ5NjEyZTE0MjQyZjJiOGYyZGUwMDE0NDYzYzE4ZTUwMWIxMzkyNjdkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8gdxDSZ_gYfiPscdsxTUXKGTsc3VNi8jzIFPnnYDoSI)

Still ongoing issue on 
commit 2a0ff47

using total amount instead of order amount (strategy using it as order amount)
![image](https://github.com/user-attachments/assets/9a6f02f1-4ef9-4eee-8749-9dc03d8d5b11)

2024-12-26 14:11 UTC, cardosofede commented
@nikspz that is expected if the price is below the limit price

2024-12-26 14:23 UTC, nikspz commented
> @nikspz that is expected if the price is below the limit price

yes, just noticed config not saved for some reason, so I pushed old 😬 very strange, I was sure to set it up for new values. 
Checked on binance it worked, I thought may related to hyperliquid changes.

retested on this config, should work
[hypg3.zip](https://github.com/user-attachments/files/18253380/hypg3.zip)

![image](https://github.com/user-attachments/assets/a32a939f-f45e-4603-9b7e-8c69e65f47bd)
![image](https://github.com/user-attachments/assets/f4c453fb-249e-4579-a7e7-be7a7376f86d)

2024-12-26 16:24 UTC, nikspz approved these changes
arbitrage_controller Tests:
- Cloned and installed PR7316
- create create --controller-config arbitrage_controller, using mexc and uniswap_ethereum_base ✅
- create --script-config v2_with_controllers using this controller
- started the script successfully, review both buy and sell filled successfully ✅
- No error showed during buy / sell cycle filled ✅

Grid strike grid component:
changed hyperliquid config and review could run successfully ✅
Observe start price, end_price and limit_price is ok and placed according to config ✅
Ran bot for ~2 hours on binance / hyperliquid spot: ok ✅



Note: total_amount_quote changed for all so arb controller use it too (used for order amount)

2024-12-26 17:34 UTC, fengtality commented
let's merge this into `development` and proceed with the release unless @cardosofede has more changes

2024-12-26 17:51 UTC, merged